// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appmessage.proto

package messages;

public final class Appmessage {
  private Appmessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AppMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes content = 1;
    /**
     * <code>required bytes content = 1;</code>
     */
    boolean hasContent();
    /**
     * <code>required bytes content = 1;</code>
     */
    com.google.protobuf.ByteString getContent();

    // required bytes signature = 2;
    /**
     * <code>required bytes signature = 2;</code>
     *
     * <pre>
     * On the receiving end, remember to check the signature with crypto_sign_verify_detached
     * </pre>
     */
    boolean hasSignature();
    /**
     * <code>required bytes signature = 2;</code>
     *
     * <pre>
     * On the receiving end, remember to check the signature with crypto_sign_verify_detached
     * </pre>
     */
    com.google.protobuf.ByteString getSignature();

    // required bytes temppublic_key = 3;
    /**
     * <code>required bytes temppublic_key = 3;</code>
     *
     * <pre>
     * Pretty sure this is own public key needed to check signature
     * </pre>
     */
    boolean hasTemppublicKey();
    /**
     * <code>required bytes temppublic_key = 3;</code>
     *
     * <pre>
     * Pretty sure this is own public key needed to check signature
     * </pre>
     */
    com.google.protobuf.ByteString getTemppublicKey();
  }
  /**
   * Protobuf type {@code messages.AppMessage}
   */
  public static final class AppMessage extends
      com.google.protobuf.GeneratedMessage
      implements AppMessageOrBuilder {
    // Use AppMessage.newBuilder() to construct.
    private AppMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AppMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AppMessage defaultInstance;
    public static AppMessage getDefaultInstance() {
      return defaultInstance;
    }

    public AppMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AppMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              content_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              signature_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              temppublicKey_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return messages.Appmessage.internal_static_messages_AppMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return messages.Appmessage.internal_static_messages_AppMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              messages.Appmessage.AppMessage.class, messages.Appmessage.AppMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<AppMessage> PARSER =
        new com.google.protobuf.AbstractParser<AppMessage>() {
      public AppMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AppMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes content = 1;
    public static final int CONTENT_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>required bytes content = 1;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes content = 1;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    // required bytes signature = 2;
    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>required bytes signature = 2;</code>
     *
     * <pre>
     * On the receiving end, remember to check the signature with crypto_sign_verify_detached
     * </pre>
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes signature = 2;</code>
     *
     * <pre>
     * On the receiving end, remember to check the signature with crypto_sign_verify_detached
     * </pre>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    // required bytes temppublic_key = 3;
    public static final int TEMPPUBLIC_KEY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString temppublicKey_;
    /**
     * <code>required bytes temppublic_key = 3;</code>
     *
     * <pre>
     * Pretty sure this is own public key needed to check signature
     * </pre>
     */
    public boolean hasTemppublicKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes temppublic_key = 3;</code>
     *
     * <pre>
     * Pretty sure this is own public key needed to check signature
     * </pre>
     */
    public com.google.protobuf.ByteString getTemppublicKey() {
      return temppublicKey_;
    }

    private void initFields() {
      content_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
      temppublicKey_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSignature()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTemppublicKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, content_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, signature_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, temppublicKey_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, content_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, signature_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, temppublicKey_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static messages.Appmessage.AppMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Appmessage.AppMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Appmessage.AppMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Appmessage.AppMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Appmessage.AppMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static messages.Appmessage.AppMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static messages.Appmessage.AppMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static messages.Appmessage.AppMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static messages.Appmessage.AppMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static messages.Appmessage.AppMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(messages.Appmessage.AppMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.AppMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements messages.Appmessage.AppMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return messages.Appmessage.internal_static_messages_AppMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return messages.Appmessage.internal_static_messages_AppMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                messages.Appmessage.AppMessage.class, messages.Appmessage.AppMessage.Builder.class);
      }

      // Construct using messages.Appmessage.AppMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        signature_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        temppublicKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return messages.Appmessage.internal_static_messages_AppMessage_descriptor;
      }

      public messages.Appmessage.AppMessage getDefaultInstanceForType() {
        return messages.Appmessage.AppMessage.getDefaultInstance();
      }

      public messages.Appmessage.AppMessage build() {
        messages.Appmessage.AppMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public messages.Appmessage.AppMessage buildPartial() {
        messages.Appmessage.AppMessage result = new messages.Appmessage.AppMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.signature_ = signature_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.temppublicKey_ = temppublicKey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof messages.Appmessage.AppMessage) {
          return mergeFrom((messages.Appmessage.AppMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(messages.Appmessage.AppMessage other) {
        if (other == messages.Appmessage.AppMessage.getDefaultInstance()) return this;
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        if (other.hasSignature()) {
          setSignature(other.getSignature());
        }
        if (other.hasTemppublicKey()) {
          setTemppublicKey(other.getTemppublicKey());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasContent()) {
          
          return false;
        }
        if (!hasSignature()) {
          
          return false;
        }
        if (!hasTemppublicKey()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        messages.Appmessage.AppMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (messages.Appmessage.AppMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes content = 1;
      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes content = 1;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes content = 1;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>required bytes content = 1;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes content = 1;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      // required bytes signature = 2;
      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes signature = 2;</code>
       *
       * <pre>
       * On the receiving end, remember to check the signature with crypto_sign_verify_detached
       * </pre>
       */
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes signature = 2;</code>
       *
       * <pre>
       * On the receiving end, remember to check the signature with crypto_sign_verify_detached
       * </pre>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>required bytes signature = 2;</code>
       *
       * <pre>
       * On the receiving end, remember to check the signature with crypto_sign_verify_detached
       * </pre>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes signature = 2;</code>
       *
       * <pre>
       * On the receiving end, remember to check the signature with crypto_sign_verify_detached
       * </pre>
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000002);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }

      // required bytes temppublic_key = 3;
      private com.google.protobuf.ByteString temppublicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes temppublic_key = 3;</code>
       *
       * <pre>
       * Pretty sure this is own public key needed to check signature
       * </pre>
       */
      public boolean hasTemppublicKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes temppublic_key = 3;</code>
       *
       * <pre>
       * Pretty sure this is own public key needed to check signature
       * </pre>
       */
      public com.google.protobuf.ByteString getTemppublicKey() {
        return temppublicKey_;
      }
      /**
       * <code>required bytes temppublic_key = 3;</code>
       *
       * <pre>
       * Pretty sure this is own public key needed to check signature
       * </pre>
       */
      public Builder setTemppublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        temppublicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes temppublic_key = 3;</code>
       *
       * <pre>
       * Pretty sure this is own public key needed to check signature
       * </pre>
       */
      public Builder clearTemppublicKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        temppublicKey_ = getDefaultInstance().getTemppublicKey();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:messages.AppMessage)
    }

    static {
      defaultInstance = new AppMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messages.AppMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_AppMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_AppMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020appmessage.proto\022\010messages\"H\n\nAppMessa" +
      "ge\022\017\n\007content\030\001 \002(\014\022\021\n\tsignature\030\002 \002(\014\022\026" +
      "\n\016temppublic_key\030\003 \002(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_messages_AppMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_messages_AppMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_AppMessage_descriptor,
              new java.lang.String[] { "Content", "Signature", "TemppublicKey", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
