// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basemessage.proto

package messages;

public final class Basemessage {
  private Basemessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BaseMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .messages.BaseMessage.Type type = 1;
    /**
     * <code>required .messages.BaseMessage.Type type = 1;</code>
     *
     * <pre>
     * Identifies which field is filled in.
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required .messages.BaseMessage.Type type = 1;</code>
     *
     * <pre>
     * Identifies which field is filled in.
     * </pre>
     */
    messages.Basemessage.BaseMessage.Type getType();

    // optional .messages.ServerHello serverHello = 2;
    /**
     * <code>optional .messages.ServerHello serverHello = 2;</code>
     *
     * <pre>
     * One of the following will be filled in.
     * </pre>
     */
    boolean hasServerHello();
    /**
     * <code>optional .messages.ServerHello serverHello = 2;</code>
     *
     * <pre>
     * One of the following will be filled in.
     * </pre>
     */
    messages.Serverhello.ServerHello getServerHello();
    /**
     * <code>optional .messages.ServerHello serverHello = 2;</code>
     *
     * <pre>
     * One of the following will be filled in.
     * </pre>
     */
    messages.Serverhello.ServerHelloOrBuilder getServerHelloOrBuilder();

    // optional .messages.ClientHello clientHello = 3;
    /**
     * <code>optional .messages.ClientHello clientHello = 3;</code>
     */
    boolean hasClientHello();
    /**
     * <code>optional .messages.ClientHello clientHello = 3;</code>
     */
    messages.Clienthello.ClientHello getClientHello();
    /**
     * <code>optional .messages.ClientHello clientHello = 3;</code>
     */
    messages.Clienthello.ClientHelloOrBuilder getClientHelloOrBuilder();

    // optional .messages.Subscribe subscribe = 4;
    /**
     * <code>optional .messages.Subscribe subscribe = 4;</code>
     */
    boolean hasSubscribe();
    /**
     * <code>optional .messages.Subscribe subscribe = 4;</code>
     */
    messages.Facademessages.Subscribe getSubscribe();
    /**
     * <code>optional .messages.Subscribe subscribe = 4;</code>
     */
    messages.Facademessages.SubscribeOrBuilder getSubscribeOrBuilder();

    // optional .messages.DatabaseInterface database = 5;
    /**
     * <code>optional .messages.DatabaseInterface database = 5;</code>
     */
    boolean hasDatabase();
    /**
     * <code>optional .messages.DatabaseInterface database = 5;</code>
     */
    messages.Databaseinterface.DatabaseInterface getDatabase();
    /**
     * <code>optional .messages.DatabaseInterface database = 5;</code>
     */
    messages.Databaseinterface.DatabaseInterfaceOrBuilder getDatabaseOrBuilder();

    // optional .messages.LedgerInterface ledger = 6;
    /**
     * <code>optional .messages.LedgerInterface ledger = 6;</code>
     */
    boolean hasLedger();
    /**
     * <code>optional .messages.LedgerInterface ledger = 6;</code>
     */
    messages.Ledgerinterface.LedgerInterface getLedger();
    /**
     * <code>optional .messages.LedgerInterface ledger = 6;</code>
     */
    messages.Ledgerinterface.LedgerInterfaceOrBuilder getLedgerOrBuilder();

    // optional .messages.StatusMessage status = 7;
    /**
     * <code>optional .messages.StatusMessage status = 7;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional .messages.StatusMessage status = 7;</code>
     */
    messages.Statusmessage.StatusMessage getStatus();
    /**
     * <code>optional .messages.StatusMessage status = 7;</code>
     */
    messages.Statusmessage.StatusMessageOrBuilder getStatusOrBuilder();

    // optional .messages.AckInterface ack = 8;
    /**
     * <code>optional .messages.AckInterface ack = 8;</code>
     */
    boolean hasAck();
    /**
     * <code>optional .messages.AckInterface ack = 8;</code>
     */
    messages.Ackinterface.AckInterface getAck();
    /**
     * <code>optional .messages.AckInterface ack = 8;</code>
     */
    messages.Ackinterface.AckInterfaceOrBuilder getAckOrBuilder();
  }
  /**
   * Protobuf type {@code messages.BaseMessage}
   */
  public static final class BaseMessage extends
      com.google.protobuf.GeneratedMessage
      implements BaseMessageOrBuilder {
    // Use BaseMessage.newBuilder() to construct.
    private BaseMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BaseMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BaseMessage defaultInstance;
    public static BaseMessage getDefaultInstance() {
      return defaultInstance;
    }

    public BaseMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BaseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              messages.Basemessage.BaseMessage.Type value = messages.Basemessage.BaseMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              messages.Serverhello.ServerHello.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = serverHello_.toBuilder();
              }
              serverHello_ = input.readMessage(messages.Serverhello.ServerHello.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(serverHello_);
                serverHello_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              messages.Clienthello.ClientHello.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = clientHello_.toBuilder();
              }
              clientHello_ = input.readMessage(messages.Clienthello.ClientHello.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(clientHello_);
                clientHello_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              messages.Facademessages.Subscribe.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = subscribe_.toBuilder();
              }
              subscribe_ = input.readMessage(messages.Facademessages.Subscribe.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(subscribe_);
                subscribe_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 42: {
              messages.Databaseinterface.DatabaseInterface.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = database_.toBuilder();
              }
              database_ = input.readMessage(messages.Databaseinterface.DatabaseInterface.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(database_);
                database_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 50: {
              messages.Ledgerinterface.LedgerInterface.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = ledger_.toBuilder();
              }
              ledger_ = input.readMessage(messages.Ledgerinterface.LedgerInterface.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ledger_);
                ledger_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
            case 58: {
              messages.Statusmessage.StatusMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) == 0x00000040)) {
                subBuilder = status_.toBuilder();
              }
              status_ = input.readMessage(messages.Statusmessage.StatusMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(status_);
                status_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
            case 66: {
              messages.Ackinterface.AckInterface.Builder subBuilder = null;
              if (((bitField0_ & 0x00000080) == 0x00000080)) {
                subBuilder = ack_.toBuilder();
              }
              ack_ = input.readMessage(messages.Ackinterface.AckInterface.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ack_);
                ack_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000080;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return messages.Basemessage.internal_static_messages_BaseMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return messages.Basemessage.internal_static_messages_BaseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              messages.Basemessage.BaseMessage.class, messages.Basemessage.BaseMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<BaseMessage> PARSER =
        new com.google.protobuf.AbstractParser<BaseMessage>() {
      public BaseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BaseMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code messages.BaseMessage.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SERVERHELLO = 1;</code>
       */
      SERVERHELLO(0, 1),
      /**
       * <code>CLIENTHELLO = 2;</code>
       */
      CLIENTHELLO(1, 2),
      /**
       * <code>SUBSCRIBE = 3;</code>
       */
      SUBSCRIBE(2, 3),
      /**
       * <code>DATABASE = 4;</code>
       */
      DATABASE(3, 4),
      /**
       * <code>LEDGER = 5;</code>
       */
      LEDGER(4, 5),
      /**
       * <code>STATUS = 6;</code>
       */
      STATUS(5, 6),
      /**
       * <code>ACK = 7;</code>
       */
      ACK(6, 7),
      ;

      /**
       * <code>SERVERHELLO = 1;</code>
       */
      public static final int SERVERHELLO_VALUE = 1;
      /**
       * <code>CLIENTHELLO = 2;</code>
       */
      public static final int CLIENTHELLO_VALUE = 2;
      /**
       * <code>SUBSCRIBE = 3;</code>
       */
      public static final int SUBSCRIBE_VALUE = 3;
      /**
       * <code>DATABASE = 4;</code>
       */
      public static final int DATABASE_VALUE = 4;
      /**
       * <code>LEDGER = 5;</code>
       */
      public static final int LEDGER_VALUE = 5;
      /**
       * <code>STATUS = 6;</code>
       */
      public static final int STATUS_VALUE = 6;
      /**
       * <code>ACK = 7;</code>
       */
      public static final int ACK_VALUE = 7;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return SERVERHELLO;
          case 2: return CLIENTHELLO;
          case 3: return SUBSCRIBE;
          case 4: return DATABASE;
          case 5: return LEDGER;
          case 6: return STATUS;
          case 7: return ACK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return messages.Basemessage.BaseMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:messages.BaseMessage.Type)
    }

    private int bitField0_;
    // required .messages.BaseMessage.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private messages.Basemessage.BaseMessage.Type type_;
    /**
     * <code>required .messages.BaseMessage.Type type = 1;</code>
     *
     * <pre>
     * Identifies which field is filled in.
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .messages.BaseMessage.Type type = 1;</code>
     *
     * <pre>
     * Identifies which field is filled in.
     * </pre>
     */
    public messages.Basemessage.BaseMessage.Type getType() {
      return type_;
    }

    // optional .messages.ServerHello serverHello = 2;
    public static final int SERVERHELLO_FIELD_NUMBER = 2;
    private messages.Serverhello.ServerHello serverHello_;
    /**
     * <code>optional .messages.ServerHello serverHello = 2;</code>
     *
     * <pre>
     * One of the following will be filled in.
     * </pre>
     */
    public boolean hasServerHello() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .messages.ServerHello serverHello = 2;</code>
     *
     * <pre>
     * One of the following will be filled in.
     * </pre>
     */
    public messages.Serverhello.ServerHello getServerHello() {
      return serverHello_;
    }
    /**
     * <code>optional .messages.ServerHello serverHello = 2;</code>
     *
     * <pre>
     * One of the following will be filled in.
     * </pre>
     */
    public messages.Serverhello.ServerHelloOrBuilder getServerHelloOrBuilder() {
      return serverHello_;
    }

    // optional .messages.ClientHello clientHello = 3;
    public static final int CLIENTHELLO_FIELD_NUMBER = 3;
    private messages.Clienthello.ClientHello clientHello_;
    /**
     * <code>optional .messages.ClientHello clientHello = 3;</code>
     */
    public boolean hasClientHello() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .messages.ClientHello clientHello = 3;</code>
     */
    public messages.Clienthello.ClientHello getClientHello() {
      return clientHello_;
    }
    /**
     * <code>optional .messages.ClientHello clientHello = 3;</code>
     */
    public messages.Clienthello.ClientHelloOrBuilder getClientHelloOrBuilder() {
      return clientHello_;
    }

    // optional .messages.Subscribe subscribe = 4;
    public static final int SUBSCRIBE_FIELD_NUMBER = 4;
    private messages.Facademessages.Subscribe subscribe_;
    /**
     * <code>optional .messages.Subscribe subscribe = 4;</code>
     */
    public boolean hasSubscribe() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .messages.Subscribe subscribe = 4;</code>
     */
    public messages.Facademessages.Subscribe getSubscribe() {
      return subscribe_;
    }
    /**
     * <code>optional .messages.Subscribe subscribe = 4;</code>
     */
    public messages.Facademessages.SubscribeOrBuilder getSubscribeOrBuilder() {
      return subscribe_;
    }

    // optional .messages.DatabaseInterface database = 5;
    public static final int DATABASE_FIELD_NUMBER = 5;
    private messages.Databaseinterface.DatabaseInterface database_;
    /**
     * <code>optional .messages.DatabaseInterface database = 5;</code>
     */
    public boolean hasDatabase() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .messages.DatabaseInterface database = 5;</code>
     */
    public messages.Databaseinterface.DatabaseInterface getDatabase() {
      return database_;
    }
    /**
     * <code>optional .messages.DatabaseInterface database = 5;</code>
     */
    public messages.Databaseinterface.DatabaseInterfaceOrBuilder getDatabaseOrBuilder() {
      return database_;
    }

    // optional .messages.LedgerInterface ledger = 6;
    public static final int LEDGER_FIELD_NUMBER = 6;
    private messages.Ledgerinterface.LedgerInterface ledger_;
    /**
     * <code>optional .messages.LedgerInterface ledger = 6;</code>
     */
    public boolean hasLedger() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .messages.LedgerInterface ledger = 6;</code>
     */
    public messages.Ledgerinterface.LedgerInterface getLedger() {
      return ledger_;
    }
    /**
     * <code>optional .messages.LedgerInterface ledger = 6;</code>
     */
    public messages.Ledgerinterface.LedgerInterfaceOrBuilder getLedgerOrBuilder() {
      return ledger_;
    }

    // optional .messages.StatusMessage status = 7;
    public static final int STATUS_FIELD_NUMBER = 7;
    private messages.Statusmessage.StatusMessage status_;
    /**
     * <code>optional .messages.StatusMessage status = 7;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .messages.StatusMessage status = 7;</code>
     */
    public messages.Statusmessage.StatusMessage getStatus() {
      return status_;
    }
    /**
     * <code>optional .messages.StatusMessage status = 7;</code>
     */
    public messages.Statusmessage.StatusMessageOrBuilder getStatusOrBuilder() {
      return status_;
    }

    // optional .messages.AckInterface ack = 8;
    public static final int ACK_FIELD_NUMBER = 8;
    private messages.Ackinterface.AckInterface ack_;
    /**
     * <code>optional .messages.AckInterface ack = 8;</code>
     */
    public boolean hasAck() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional .messages.AckInterface ack = 8;</code>
     */
    public messages.Ackinterface.AckInterface getAck() {
      return ack_;
    }
    /**
     * <code>optional .messages.AckInterface ack = 8;</code>
     */
    public messages.Ackinterface.AckInterfaceOrBuilder getAckOrBuilder() {
      return ack_;
    }

    private void initFields() {
      type_ = messages.Basemessage.BaseMessage.Type.SERVERHELLO;
      serverHello_ = messages.Serverhello.ServerHello.getDefaultInstance();
      clientHello_ = messages.Clienthello.ClientHello.getDefaultInstance();
      subscribe_ = messages.Facademessages.Subscribe.getDefaultInstance();
      database_ = messages.Databaseinterface.DatabaseInterface.getDefaultInstance();
      ledger_ = messages.Ledgerinterface.LedgerInterface.getDefaultInstance();
      status_ = messages.Statusmessage.StatusMessage.getDefaultInstance();
      ack_ = messages.Ackinterface.AckInterface.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasServerHello()) {
        if (!getServerHello().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasClientHello()) {
        if (!getClientHello().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasSubscribe()) {
        if (!getSubscribe().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasDatabase()) {
        if (!getDatabase().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasLedger()) {
        if (!getLedger().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasStatus()) {
        if (!getStatus().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasAck()) {
        if (!getAck().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, serverHello_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, clientHello_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, subscribe_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, database_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(6, ledger_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, status_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeMessage(8, ack_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, serverHello_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, clientHello_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, subscribe_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, database_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, ledger_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, status_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, ack_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static messages.Basemessage.BaseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Basemessage.BaseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Basemessage.BaseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Basemessage.BaseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Basemessage.BaseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static messages.Basemessage.BaseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static messages.Basemessage.BaseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static messages.Basemessage.BaseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static messages.Basemessage.BaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static messages.Basemessage.BaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(messages.Basemessage.BaseMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.BaseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements messages.Basemessage.BaseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return messages.Basemessage.internal_static_messages_BaseMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return messages.Basemessage.internal_static_messages_BaseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                messages.Basemessage.BaseMessage.class, messages.Basemessage.BaseMessage.Builder.class);
      }

      // Construct using messages.Basemessage.BaseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getServerHelloFieldBuilder();
          getClientHelloFieldBuilder();
          getSubscribeFieldBuilder();
          getDatabaseFieldBuilder();
          getLedgerFieldBuilder();
          getStatusFieldBuilder();
          getAckFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = messages.Basemessage.BaseMessage.Type.SERVERHELLO;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (serverHelloBuilder_ == null) {
          serverHello_ = messages.Serverhello.ServerHello.getDefaultInstance();
        } else {
          serverHelloBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (clientHelloBuilder_ == null) {
          clientHello_ = messages.Clienthello.ClientHello.getDefaultInstance();
        } else {
          clientHelloBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (subscribeBuilder_ == null) {
          subscribe_ = messages.Facademessages.Subscribe.getDefaultInstance();
        } else {
          subscribeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (databaseBuilder_ == null) {
          database_ = messages.Databaseinterface.DatabaseInterface.getDefaultInstance();
        } else {
          databaseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        if (ledgerBuilder_ == null) {
          ledger_ = messages.Ledgerinterface.LedgerInterface.getDefaultInstance();
        } else {
          ledgerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        if (statusBuilder_ == null) {
          status_ = messages.Statusmessage.StatusMessage.getDefaultInstance();
        } else {
          statusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        if (ackBuilder_ == null) {
          ack_ = messages.Ackinterface.AckInterface.getDefaultInstance();
        } else {
          ackBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return messages.Basemessage.internal_static_messages_BaseMessage_descriptor;
      }

      public messages.Basemessage.BaseMessage getDefaultInstanceForType() {
        return messages.Basemessage.BaseMessage.getDefaultInstance();
      }

      public messages.Basemessage.BaseMessage build() {
        messages.Basemessage.BaseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public messages.Basemessage.BaseMessage buildPartial() {
        messages.Basemessage.BaseMessage result = new messages.Basemessage.BaseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (serverHelloBuilder_ == null) {
          result.serverHello_ = serverHello_;
        } else {
          result.serverHello_ = serverHelloBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (clientHelloBuilder_ == null) {
          result.clientHello_ = clientHello_;
        } else {
          result.clientHello_ = clientHelloBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (subscribeBuilder_ == null) {
          result.subscribe_ = subscribe_;
        } else {
          result.subscribe_ = subscribeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (databaseBuilder_ == null) {
          result.database_ = database_;
        } else {
          result.database_ = databaseBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (ledgerBuilder_ == null) {
          result.ledger_ = ledger_;
        } else {
          result.ledger_ = ledgerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (statusBuilder_ == null) {
          result.status_ = status_;
        } else {
          result.status_ = statusBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        if (ackBuilder_ == null) {
          result.ack_ = ack_;
        } else {
          result.ack_ = ackBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof messages.Basemessage.BaseMessage) {
          return mergeFrom((messages.Basemessage.BaseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(messages.Basemessage.BaseMessage other) {
        if (other == messages.Basemessage.BaseMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasServerHello()) {
          mergeServerHello(other.getServerHello());
        }
        if (other.hasClientHello()) {
          mergeClientHello(other.getClientHello());
        }
        if (other.hasSubscribe()) {
          mergeSubscribe(other.getSubscribe());
        }
        if (other.hasDatabase()) {
          mergeDatabase(other.getDatabase());
        }
        if (other.hasLedger()) {
          mergeLedger(other.getLedger());
        }
        if (other.hasStatus()) {
          mergeStatus(other.getStatus());
        }
        if (other.hasAck()) {
          mergeAck(other.getAck());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasServerHello()) {
          if (!getServerHello().isInitialized()) {
            
            return false;
          }
        }
        if (hasClientHello()) {
          if (!getClientHello().isInitialized()) {
            
            return false;
          }
        }
        if (hasSubscribe()) {
          if (!getSubscribe().isInitialized()) {
            
            return false;
          }
        }
        if (hasDatabase()) {
          if (!getDatabase().isInitialized()) {
            
            return false;
          }
        }
        if (hasLedger()) {
          if (!getLedger().isInitialized()) {
            
            return false;
          }
        }
        if (hasStatus()) {
          if (!getStatus().isInitialized()) {
            
            return false;
          }
        }
        if (hasAck()) {
          if (!getAck().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        messages.Basemessage.BaseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (messages.Basemessage.BaseMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .messages.BaseMessage.Type type = 1;
      private messages.Basemessage.BaseMessage.Type type_ = messages.Basemessage.BaseMessage.Type.SERVERHELLO;
      /**
       * <code>required .messages.BaseMessage.Type type = 1;</code>
       *
       * <pre>
       * Identifies which field is filled in.
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .messages.BaseMessage.Type type = 1;</code>
       *
       * <pre>
       * Identifies which field is filled in.
       * </pre>
       */
      public messages.Basemessage.BaseMessage.Type getType() {
        return type_;
      }
      /**
       * <code>required .messages.BaseMessage.Type type = 1;</code>
       *
       * <pre>
       * Identifies which field is filled in.
       * </pre>
       */
      public Builder setType(messages.Basemessage.BaseMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .messages.BaseMessage.Type type = 1;</code>
       *
       * <pre>
       * Identifies which field is filled in.
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = messages.Basemessage.BaseMessage.Type.SERVERHELLO;
        onChanged();
        return this;
      }

      // optional .messages.ServerHello serverHello = 2;
      private messages.Serverhello.ServerHello serverHello_ = messages.Serverhello.ServerHello.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          messages.Serverhello.ServerHello, messages.Serverhello.ServerHello.Builder, messages.Serverhello.ServerHelloOrBuilder> serverHelloBuilder_;
      /**
       * <code>optional .messages.ServerHello serverHello = 2;</code>
       *
       * <pre>
       * One of the following will be filled in.
       * </pre>
       */
      public boolean hasServerHello() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .messages.ServerHello serverHello = 2;</code>
       *
       * <pre>
       * One of the following will be filled in.
       * </pre>
       */
      public messages.Serverhello.ServerHello getServerHello() {
        if (serverHelloBuilder_ == null) {
          return serverHello_;
        } else {
          return serverHelloBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .messages.ServerHello serverHello = 2;</code>
       *
       * <pre>
       * One of the following will be filled in.
       * </pre>
       */
      public Builder setServerHello(messages.Serverhello.ServerHello value) {
        if (serverHelloBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          serverHello_ = value;
          onChanged();
        } else {
          serverHelloBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .messages.ServerHello serverHello = 2;</code>
       *
       * <pre>
       * One of the following will be filled in.
       * </pre>
       */
      public Builder setServerHello(
          messages.Serverhello.ServerHello.Builder builderForValue) {
        if (serverHelloBuilder_ == null) {
          serverHello_ = builderForValue.build();
          onChanged();
        } else {
          serverHelloBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .messages.ServerHello serverHello = 2;</code>
       *
       * <pre>
       * One of the following will be filled in.
       * </pre>
       */
      public Builder mergeServerHello(messages.Serverhello.ServerHello value) {
        if (serverHelloBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              serverHello_ != messages.Serverhello.ServerHello.getDefaultInstance()) {
            serverHello_ =
              messages.Serverhello.ServerHello.newBuilder(serverHello_).mergeFrom(value).buildPartial();
          } else {
            serverHello_ = value;
          }
          onChanged();
        } else {
          serverHelloBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .messages.ServerHello serverHello = 2;</code>
       *
       * <pre>
       * One of the following will be filled in.
       * </pre>
       */
      public Builder clearServerHello() {
        if (serverHelloBuilder_ == null) {
          serverHello_ = messages.Serverhello.ServerHello.getDefaultInstance();
          onChanged();
        } else {
          serverHelloBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .messages.ServerHello serverHello = 2;</code>
       *
       * <pre>
       * One of the following will be filled in.
       * </pre>
       */
      public messages.Serverhello.ServerHello.Builder getServerHelloBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getServerHelloFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .messages.ServerHello serverHello = 2;</code>
       *
       * <pre>
       * One of the following will be filled in.
       * </pre>
       */
      public messages.Serverhello.ServerHelloOrBuilder getServerHelloOrBuilder() {
        if (serverHelloBuilder_ != null) {
          return serverHelloBuilder_.getMessageOrBuilder();
        } else {
          return serverHello_;
        }
      }
      /**
       * <code>optional .messages.ServerHello serverHello = 2;</code>
       *
       * <pre>
       * One of the following will be filled in.
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          messages.Serverhello.ServerHello, messages.Serverhello.ServerHello.Builder, messages.Serverhello.ServerHelloOrBuilder> 
          getServerHelloFieldBuilder() {
        if (serverHelloBuilder_ == null) {
          serverHelloBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              messages.Serverhello.ServerHello, messages.Serverhello.ServerHello.Builder, messages.Serverhello.ServerHelloOrBuilder>(
                  serverHello_,
                  getParentForChildren(),
                  isClean());
          serverHello_ = null;
        }
        return serverHelloBuilder_;
      }

      // optional .messages.ClientHello clientHello = 3;
      private messages.Clienthello.ClientHello clientHello_ = messages.Clienthello.ClientHello.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          messages.Clienthello.ClientHello, messages.Clienthello.ClientHello.Builder, messages.Clienthello.ClientHelloOrBuilder> clientHelloBuilder_;
      /**
       * <code>optional .messages.ClientHello clientHello = 3;</code>
       */
      public boolean hasClientHello() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .messages.ClientHello clientHello = 3;</code>
       */
      public messages.Clienthello.ClientHello getClientHello() {
        if (clientHelloBuilder_ == null) {
          return clientHello_;
        } else {
          return clientHelloBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .messages.ClientHello clientHello = 3;</code>
       */
      public Builder setClientHello(messages.Clienthello.ClientHello value) {
        if (clientHelloBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          clientHello_ = value;
          onChanged();
        } else {
          clientHelloBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .messages.ClientHello clientHello = 3;</code>
       */
      public Builder setClientHello(
          messages.Clienthello.ClientHello.Builder builderForValue) {
        if (clientHelloBuilder_ == null) {
          clientHello_ = builderForValue.build();
          onChanged();
        } else {
          clientHelloBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .messages.ClientHello clientHello = 3;</code>
       */
      public Builder mergeClientHello(messages.Clienthello.ClientHello value) {
        if (clientHelloBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              clientHello_ != messages.Clienthello.ClientHello.getDefaultInstance()) {
            clientHello_ =
              messages.Clienthello.ClientHello.newBuilder(clientHello_).mergeFrom(value).buildPartial();
          } else {
            clientHello_ = value;
          }
          onChanged();
        } else {
          clientHelloBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .messages.ClientHello clientHello = 3;</code>
       */
      public Builder clearClientHello() {
        if (clientHelloBuilder_ == null) {
          clientHello_ = messages.Clienthello.ClientHello.getDefaultInstance();
          onChanged();
        } else {
          clientHelloBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .messages.ClientHello clientHello = 3;</code>
       */
      public messages.Clienthello.ClientHello.Builder getClientHelloBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getClientHelloFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .messages.ClientHello clientHello = 3;</code>
       */
      public messages.Clienthello.ClientHelloOrBuilder getClientHelloOrBuilder() {
        if (clientHelloBuilder_ != null) {
          return clientHelloBuilder_.getMessageOrBuilder();
        } else {
          return clientHello_;
        }
      }
      /**
       * <code>optional .messages.ClientHello clientHello = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          messages.Clienthello.ClientHello, messages.Clienthello.ClientHello.Builder, messages.Clienthello.ClientHelloOrBuilder> 
          getClientHelloFieldBuilder() {
        if (clientHelloBuilder_ == null) {
          clientHelloBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              messages.Clienthello.ClientHello, messages.Clienthello.ClientHello.Builder, messages.Clienthello.ClientHelloOrBuilder>(
                  clientHello_,
                  getParentForChildren(),
                  isClean());
          clientHello_ = null;
        }
        return clientHelloBuilder_;
      }

      // optional .messages.Subscribe subscribe = 4;
      private messages.Facademessages.Subscribe subscribe_ = messages.Facademessages.Subscribe.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          messages.Facademessages.Subscribe, messages.Facademessages.Subscribe.Builder, messages.Facademessages.SubscribeOrBuilder> subscribeBuilder_;
      /**
       * <code>optional .messages.Subscribe subscribe = 4;</code>
       */
      public boolean hasSubscribe() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .messages.Subscribe subscribe = 4;</code>
       */
      public messages.Facademessages.Subscribe getSubscribe() {
        if (subscribeBuilder_ == null) {
          return subscribe_;
        } else {
          return subscribeBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .messages.Subscribe subscribe = 4;</code>
       */
      public Builder setSubscribe(messages.Facademessages.Subscribe value) {
        if (subscribeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          subscribe_ = value;
          onChanged();
        } else {
          subscribeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .messages.Subscribe subscribe = 4;</code>
       */
      public Builder setSubscribe(
          messages.Facademessages.Subscribe.Builder builderForValue) {
        if (subscribeBuilder_ == null) {
          subscribe_ = builderForValue.build();
          onChanged();
        } else {
          subscribeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .messages.Subscribe subscribe = 4;</code>
       */
      public Builder mergeSubscribe(messages.Facademessages.Subscribe value) {
        if (subscribeBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              subscribe_ != messages.Facademessages.Subscribe.getDefaultInstance()) {
            subscribe_ =
              messages.Facademessages.Subscribe.newBuilder(subscribe_).mergeFrom(value).buildPartial();
          } else {
            subscribe_ = value;
          }
          onChanged();
        } else {
          subscribeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .messages.Subscribe subscribe = 4;</code>
       */
      public Builder clearSubscribe() {
        if (subscribeBuilder_ == null) {
          subscribe_ = messages.Facademessages.Subscribe.getDefaultInstance();
          onChanged();
        } else {
          subscribeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .messages.Subscribe subscribe = 4;</code>
       */
      public messages.Facademessages.Subscribe.Builder getSubscribeBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getSubscribeFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .messages.Subscribe subscribe = 4;</code>
       */
      public messages.Facademessages.SubscribeOrBuilder getSubscribeOrBuilder() {
        if (subscribeBuilder_ != null) {
          return subscribeBuilder_.getMessageOrBuilder();
        } else {
          return subscribe_;
        }
      }
      /**
       * <code>optional .messages.Subscribe subscribe = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          messages.Facademessages.Subscribe, messages.Facademessages.Subscribe.Builder, messages.Facademessages.SubscribeOrBuilder> 
          getSubscribeFieldBuilder() {
        if (subscribeBuilder_ == null) {
          subscribeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              messages.Facademessages.Subscribe, messages.Facademessages.Subscribe.Builder, messages.Facademessages.SubscribeOrBuilder>(
                  subscribe_,
                  getParentForChildren(),
                  isClean());
          subscribe_ = null;
        }
        return subscribeBuilder_;
      }

      // optional .messages.DatabaseInterface database = 5;
      private messages.Databaseinterface.DatabaseInterface database_ = messages.Databaseinterface.DatabaseInterface.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          messages.Databaseinterface.DatabaseInterface, messages.Databaseinterface.DatabaseInterface.Builder, messages.Databaseinterface.DatabaseInterfaceOrBuilder> databaseBuilder_;
      /**
       * <code>optional .messages.DatabaseInterface database = 5;</code>
       */
      public boolean hasDatabase() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .messages.DatabaseInterface database = 5;</code>
       */
      public messages.Databaseinterface.DatabaseInterface getDatabase() {
        if (databaseBuilder_ == null) {
          return database_;
        } else {
          return databaseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .messages.DatabaseInterface database = 5;</code>
       */
      public Builder setDatabase(messages.Databaseinterface.DatabaseInterface value) {
        if (databaseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          database_ = value;
          onChanged();
        } else {
          databaseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .messages.DatabaseInterface database = 5;</code>
       */
      public Builder setDatabase(
          messages.Databaseinterface.DatabaseInterface.Builder builderForValue) {
        if (databaseBuilder_ == null) {
          database_ = builderForValue.build();
          onChanged();
        } else {
          databaseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .messages.DatabaseInterface database = 5;</code>
       */
      public Builder mergeDatabase(messages.Databaseinterface.DatabaseInterface value) {
        if (databaseBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              database_ != messages.Databaseinterface.DatabaseInterface.getDefaultInstance()) {
            database_ =
              messages.Databaseinterface.DatabaseInterface.newBuilder(database_).mergeFrom(value).buildPartial();
          } else {
            database_ = value;
          }
          onChanged();
        } else {
          databaseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .messages.DatabaseInterface database = 5;</code>
       */
      public Builder clearDatabase() {
        if (databaseBuilder_ == null) {
          database_ = messages.Databaseinterface.DatabaseInterface.getDefaultInstance();
          onChanged();
        } else {
          databaseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .messages.DatabaseInterface database = 5;</code>
       */
      public messages.Databaseinterface.DatabaseInterface.Builder getDatabaseBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getDatabaseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .messages.DatabaseInterface database = 5;</code>
       */
      public messages.Databaseinterface.DatabaseInterfaceOrBuilder getDatabaseOrBuilder() {
        if (databaseBuilder_ != null) {
          return databaseBuilder_.getMessageOrBuilder();
        } else {
          return database_;
        }
      }
      /**
       * <code>optional .messages.DatabaseInterface database = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          messages.Databaseinterface.DatabaseInterface, messages.Databaseinterface.DatabaseInterface.Builder, messages.Databaseinterface.DatabaseInterfaceOrBuilder> 
          getDatabaseFieldBuilder() {
        if (databaseBuilder_ == null) {
          databaseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              messages.Databaseinterface.DatabaseInterface, messages.Databaseinterface.DatabaseInterface.Builder, messages.Databaseinterface.DatabaseInterfaceOrBuilder>(
                  database_,
                  getParentForChildren(),
                  isClean());
          database_ = null;
        }
        return databaseBuilder_;
      }

      // optional .messages.LedgerInterface ledger = 6;
      private messages.Ledgerinterface.LedgerInterface ledger_ = messages.Ledgerinterface.LedgerInterface.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          messages.Ledgerinterface.LedgerInterface, messages.Ledgerinterface.LedgerInterface.Builder, messages.Ledgerinterface.LedgerInterfaceOrBuilder> ledgerBuilder_;
      /**
       * <code>optional .messages.LedgerInterface ledger = 6;</code>
       */
      public boolean hasLedger() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .messages.LedgerInterface ledger = 6;</code>
       */
      public messages.Ledgerinterface.LedgerInterface getLedger() {
        if (ledgerBuilder_ == null) {
          return ledger_;
        } else {
          return ledgerBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .messages.LedgerInterface ledger = 6;</code>
       */
      public Builder setLedger(messages.Ledgerinterface.LedgerInterface value) {
        if (ledgerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ledger_ = value;
          onChanged();
        } else {
          ledgerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .messages.LedgerInterface ledger = 6;</code>
       */
      public Builder setLedger(
          messages.Ledgerinterface.LedgerInterface.Builder builderForValue) {
        if (ledgerBuilder_ == null) {
          ledger_ = builderForValue.build();
          onChanged();
        } else {
          ledgerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .messages.LedgerInterface ledger = 6;</code>
       */
      public Builder mergeLedger(messages.Ledgerinterface.LedgerInterface value) {
        if (ledgerBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              ledger_ != messages.Ledgerinterface.LedgerInterface.getDefaultInstance()) {
            ledger_ =
              messages.Ledgerinterface.LedgerInterface.newBuilder(ledger_).mergeFrom(value).buildPartial();
          } else {
            ledger_ = value;
          }
          onChanged();
        } else {
          ledgerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .messages.LedgerInterface ledger = 6;</code>
       */
      public Builder clearLedger() {
        if (ledgerBuilder_ == null) {
          ledger_ = messages.Ledgerinterface.LedgerInterface.getDefaultInstance();
          onChanged();
        } else {
          ledgerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .messages.LedgerInterface ledger = 6;</code>
       */
      public messages.Ledgerinterface.LedgerInterface.Builder getLedgerBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getLedgerFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .messages.LedgerInterface ledger = 6;</code>
       */
      public messages.Ledgerinterface.LedgerInterfaceOrBuilder getLedgerOrBuilder() {
        if (ledgerBuilder_ != null) {
          return ledgerBuilder_.getMessageOrBuilder();
        } else {
          return ledger_;
        }
      }
      /**
       * <code>optional .messages.LedgerInterface ledger = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          messages.Ledgerinterface.LedgerInterface, messages.Ledgerinterface.LedgerInterface.Builder, messages.Ledgerinterface.LedgerInterfaceOrBuilder> 
          getLedgerFieldBuilder() {
        if (ledgerBuilder_ == null) {
          ledgerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              messages.Ledgerinterface.LedgerInterface, messages.Ledgerinterface.LedgerInterface.Builder, messages.Ledgerinterface.LedgerInterfaceOrBuilder>(
                  ledger_,
                  getParentForChildren(),
                  isClean());
          ledger_ = null;
        }
        return ledgerBuilder_;
      }

      // optional .messages.StatusMessage status = 7;
      private messages.Statusmessage.StatusMessage status_ = messages.Statusmessage.StatusMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          messages.Statusmessage.StatusMessage, messages.Statusmessage.StatusMessage.Builder, messages.Statusmessage.StatusMessageOrBuilder> statusBuilder_;
      /**
       * <code>optional .messages.StatusMessage status = 7;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .messages.StatusMessage status = 7;</code>
       */
      public messages.Statusmessage.StatusMessage getStatus() {
        if (statusBuilder_ == null) {
          return status_;
        } else {
          return statusBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .messages.StatusMessage status = 7;</code>
       */
      public Builder setStatus(messages.Statusmessage.StatusMessage value) {
        if (statusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          status_ = value;
          onChanged();
        } else {
          statusBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .messages.StatusMessage status = 7;</code>
       */
      public Builder setStatus(
          messages.Statusmessage.StatusMessage.Builder builderForValue) {
        if (statusBuilder_ == null) {
          status_ = builderForValue.build();
          onChanged();
        } else {
          statusBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .messages.StatusMessage status = 7;</code>
       */
      public Builder mergeStatus(messages.Statusmessage.StatusMessage value) {
        if (statusBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              status_ != messages.Statusmessage.StatusMessage.getDefaultInstance()) {
            status_ =
              messages.Statusmessage.StatusMessage.newBuilder(status_).mergeFrom(value).buildPartial();
          } else {
            status_ = value;
          }
          onChanged();
        } else {
          statusBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .messages.StatusMessage status = 7;</code>
       */
      public Builder clearStatus() {
        if (statusBuilder_ == null) {
          status_ = messages.Statusmessage.StatusMessage.getDefaultInstance();
          onChanged();
        } else {
          statusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>optional .messages.StatusMessage status = 7;</code>
       */
      public messages.Statusmessage.StatusMessage.Builder getStatusBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getStatusFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .messages.StatusMessage status = 7;</code>
       */
      public messages.Statusmessage.StatusMessageOrBuilder getStatusOrBuilder() {
        if (statusBuilder_ != null) {
          return statusBuilder_.getMessageOrBuilder();
        } else {
          return status_;
        }
      }
      /**
       * <code>optional .messages.StatusMessage status = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          messages.Statusmessage.StatusMessage, messages.Statusmessage.StatusMessage.Builder, messages.Statusmessage.StatusMessageOrBuilder> 
          getStatusFieldBuilder() {
        if (statusBuilder_ == null) {
          statusBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              messages.Statusmessage.StatusMessage, messages.Statusmessage.StatusMessage.Builder, messages.Statusmessage.StatusMessageOrBuilder>(
                  status_,
                  getParentForChildren(),
                  isClean());
          status_ = null;
        }
        return statusBuilder_;
      }

      // optional .messages.AckInterface ack = 8;
      private messages.Ackinterface.AckInterface ack_ = messages.Ackinterface.AckInterface.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          messages.Ackinterface.AckInterface, messages.Ackinterface.AckInterface.Builder, messages.Ackinterface.AckInterfaceOrBuilder> ackBuilder_;
      /**
       * <code>optional .messages.AckInterface ack = 8;</code>
       */
      public boolean hasAck() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .messages.AckInterface ack = 8;</code>
       */
      public messages.Ackinterface.AckInterface getAck() {
        if (ackBuilder_ == null) {
          return ack_;
        } else {
          return ackBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .messages.AckInterface ack = 8;</code>
       */
      public Builder setAck(messages.Ackinterface.AckInterface value) {
        if (ackBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ack_ = value;
          onChanged();
        } else {
          ackBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .messages.AckInterface ack = 8;</code>
       */
      public Builder setAck(
          messages.Ackinterface.AckInterface.Builder builderForValue) {
        if (ackBuilder_ == null) {
          ack_ = builderForValue.build();
          onChanged();
        } else {
          ackBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .messages.AckInterface ack = 8;</code>
       */
      public Builder mergeAck(messages.Ackinterface.AckInterface value) {
        if (ackBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080) &&
              ack_ != messages.Ackinterface.AckInterface.getDefaultInstance()) {
            ack_ =
              messages.Ackinterface.AckInterface.newBuilder(ack_).mergeFrom(value).buildPartial();
          } else {
            ack_ = value;
          }
          onChanged();
        } else {
          ackBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .messages.AckInterface ack = 8;</code>
       */
      public Builder clearAck() {
        if (ackBuilder_ == null) {
          ack_ = messages.Ackinterface.AckInterface.getDefaultInstance();
          onChanged();
        } else {
          ackBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      /**
       * <code>optional .messages.AckInterface ack = 8;</code>
       */
      public messages.Ackinterface.AckInterface.Builder getAckBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getAckFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .messages.AckInterface ack = 8;</code>
       */
      public messages.Ackinterface.AckInterfaceOrBuilder getAckOrBuilder() {
        if (ackBuilder_ != null) {
          return ackBuilder_.getMessageOrBuilder();
        } else {
          return ack_;
        }
      }
      /**
       * <code>optional .messages.AckInterface ack = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          messages.Ackinterface.AckInterface, messages.Ackinterface.AckInterface.Builder, messages.Ackinterface.AckInterfaceOrBuilder> 
          getAckFieldBuilder() {
        if (ackBuilder_ == null) {
          ackBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              messages.Ackinterface.AckInterface, messages.Ackinterface.AckInterface.Builder, messages.Ackinterface.AckInterfaceOrBuilder>(
                  ack_,
                  getParentForChildren(),
                  isClean());
          ack_ = null;
        }
        return ackBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:messages.BaseMessage)
    }

    static {
      defaultInstance = new BaseMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messages.BaseMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_BaseMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_BaseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021basemessage.proto\022\010messages\032\021serverhel" +
      "lo.proto\032\021clienthello.proto\032\024facademessa" +
      "ges.proto\032\027databaseinterface.proto\032\025ledg" +
      "erinterface.proto\032\023statusmessage.proto\032\022" +
      "ackinterface.proto\"\307\003\n\013BaseMessage\022(\n\004ty" +
      "pe\030\001 \002(\0162\032.messages.BaseMessage.Type\022*\n\013" +
      "serverHello\030\002 \001(\0132\025.messages.ServerHello" +
      "\022*\n\013clientHello\030\003 \001(\0132\025.messages.ClientH" +
      "ello\022&\n\tsubscribe\030\004 \001(\0132\023.messages.Subsc" +
      "ribe\022-\n\010database\030\005 \001(\0132\033.messages.Databa",
      "seInterface\022)\n\006ledger\030\006 \001(\0132\031.messages.L" +
      "edgerInterface\022\'\n\006status\030\007 \001(\0132\027.message" +
      "s.StatusMessage\022#\n\003ack\030\010 \001(\0132\026.messages." +
      "AckInterface\"f\n\004Type\022\017\n\013SERVERHELLO\020\001\022\017\n" +
      "\013CLIENTHELLO\020\002\022\r\n\tSUBSCRIBE\020\003\022\014\n\010DATABAS" +
      "E\020\004\022\n\n\006LEDGER\020\005\022\n\n\006STATUS\020\006\022\007\n\003ACK\020\007P\000P\001" +
      "P\002P\003P\004P\005P\006"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_messages_BaseMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_messages_BaseMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_BaseMessage_descriptor,
              new java.lang.String[] { "Type", "ServerHello", "ClientHello", "Subscribe", "Database", "Ledger", "Status", "Ack", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          messages.Serverhello.getDescriptor(),
          messages.Clienthello.getDescriptor(),
          messages.Facademessages.getDescriptor(),
          messages.Databaseinterface.getDescriptor(),
          messages.Ledgerinterface.getDescriptor(),
          messages.Statusmessage.getDescriptor(),
          messages.Ackinterface.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
