// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clienthello.proto

package messages;

public final class Clienthello {
  private Clienthello() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClientHelloOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes client_connection_public_key = 1;
    /**
     * <code>required bytes client_connection_public_key = 1;</code>
     *
     * <pre>
     * provide the pk generated in ClientHello.Handshake.client_connection_public_key to enable the server to decrypt the handshake message
     * </pre>
     */
    boolean hasClientConnectionPublicKey();
    /**
     * <code>required bytes client_connection_public_key = 1;</code>
     *
     * <pre>
     * provide the pk generated in ClientHello.Handshake.client_connection_public_key to enable the server to decrypt the handshake message
     * </pre>
     */
    com.google.protobuf.ByteString getClientConnectionPublicKey();

    // required bytes encrypted_handshake = 2;
    /**
     * <code>required bytes encrypted_handshake = 2;</code>
     *
     * <pre>
     * crypto_box_easy(sk=connection_public_key, pk=ServerHello.connection_public_key, nonce=[random], msg=SignedHandshake)
     * </pre>
     */
    boolean hasEncryptedHandshake();
    /**
     * <code>required bytes encrypted_handshake = 2;</code>
     *
     * <pre>
     * crypto_box_easy(sk=connection_public_key, pk=ServerHello.connection_public_key, nonce=[random], msg=SignedHandshake)
     * </pre>
     */
    com.google.protobuf.ByteString getEncryptedHandshake();
  }
  /**
   * Protobuf type {@code messages.ClientHello}
   *
   * <pre>
   * sent in response to a ServerHello used to establish an encrypted connection
   * </pre>
   */
  public static final class ClientHello extends
      com.google.protobuf.GeneratedMessage
      implements ClientHelloOrBuilder {
    // Use ClientHello.newBuilder() to construct.
    private ClientHello(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClientHello(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClientHello defaultInstance;
    public static ClientHello getDefaultInstance() {
      return defaultInstance;
    }

    public ClientHello getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClientHello(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              clientConnectionPublicKey_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              encryptedHandshake_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return messages.Clienthello.internal_static_messages_ClientHello_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return messages.Clienthello.internal_static_messages_ClientHello_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              messages.Clienthello.ClientHello.class, messages.Clienthello.ClientHello.Builder.class);
    }

    public static com.google.protobuf.Parser<ClientHello> PARSER =
        new com.google.protobuf.AbstractParser<ClientHello>() {
      public ClientHello parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientHello(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientHello> getParserForType() {
      return PARSER;
    }

    public interface HandshakeOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string message_type = 1;
      /**
       * <code>required string message_type = 1;</code>
       *
       * <pre>
       * opcode must always be set to "ClientHello.Handshake" to provide context for the signature and to prevent replay attacks
       * </pre>
       */
      boolean hasMessageType();
      /**
       * <code>required string message_type = 1;</code>
       *
       * <pre>
       * opcode must always be set to "ClientHello.Handshake" to provide context for the signature and to prevent replay attacks
       * </pre>
       */
      java.lang.String getMessageType();
      /**
       * <code>required string message_type = 1;</code>
       *
       * <pre>
       * opcode must always be set to "ClientHello.Handshake" to provide context for the signature and to prevent replay attacks
       * </pre>
       */
      com.google.protobuf.ByteString
          getMessageTypeBytes();

      // required bytes client_connection_public_key = 2;
      /**
       * <code>required bytes client_connection_public_key = 2;</code>
       *
       * <pre>
       * generated using crypto_box_keypair()
       * </pre>
       */
      boolean hasClientConnectionPublicKey();
      /**
       * <code>required bytes client_connection_public_key = 2;</code>
       *
       * <pre>
       * generated using crypto_box_keypair()
       * </pre>
       */
      com.google.protobuf.ByteString getClientConnectionPublicKey();

      // required bytes hashed_server_hello = 3;
      /**
       * <code>required bytes hashed_server_hello = 3;</code>
       *
       * <pre>
       * a SHA256 hash of the received ServerHello message
       * The ClientHello includes a hash of the ServerHello to prevent replay attacks.
       * </pre>
       */
      boolean hasHashedServerHello();
      /**
       * <code>required bytes hashed_server_hello = 3;</code>
       *
       * <pre>
       * a SHA256 hash of the received ServerHello message
       * The ClientHello includes a hash of the ServerHello to prevent replay attacks.
       * </pre>
       */
      com.google.protobuf.ByteString getHashedServerHello();

      // required int32 length_of_server_hello = 4;
      /**
       * <code>required int32 length_of_server_hello = 4;</code>
       *
       * <pre>
       * the length of the ServerHello message in bytes
       * </pre>
       */
      boolean hasLengthOfServerHello();
      /**
       * <code>required int32 length_of_server_hello = 4;</code>
       *
       * <pre>
       * the length of the ServerHello message in bytes
       * </pre>
       */
      int getLengthOfServerHello();
    }
    /**
     * Protobuf type {@code messages.ClientHello.Handshake}
     */
    public static final class Handshake extends
        com.google.protobuf.GeneratedMessage
        implements HandshakeOrBuilder {
      // Use Handshake.newBuilder() to construct.
      private Handshake(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Handshake(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Handshake defaultInstance;
      public static Handshake getDefaultInstance() {
        return defaultInstance;
      }

      public Handshake getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Handshake(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                messageType_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                clientConnectionPublicKey_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                hashedServerHello_ = input.readBytes();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                lengthOfServerHello_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return messages.Clienthello.internal_static_messages_ClientHello_Handshake_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return messages.Clienthello.internal_static_messages_ClientHello_Handshake_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                messages.Clienthello.ClientHello.Handshake.class, messages.Clienthello.ClientHello.Handshake.Builder.class);
      }

      public static com.google.protobuf.Parser<Handshake> PARSER =
          new com.google.protobuf.AbstractParser<Handshake>() {
        public Handshake parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Handshake(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Handshake> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string message_type = 1;
      public static final int MESSAGE_TYPE_FIELD_NUMBER = 1;
      private java.lang.Object messageType_;
      /**
       * <code>required string message_type = 1;</code>
       *
       * <pre>
       * opcode must always be set to "ClientHello.Handshake" to provide context for the signature and to prevent replay attacks
       * </pre>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string message_type = 1;</code>
       *
       * <pre>
       * opcode must always be set to "ClientHello.Handshake" to provide context for the signature and to prevent replay attacks
       * </pre>
       */
      public java.lang.String getMessageType() {
        java.lang.Object ref = messageType_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            messageType_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string message_type = 1;</code>
       *
       * <pre>
       * opcode must always be set to "ClientHello.Handshake" to provide context for the signature and to prevent replay attacks
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMessageTypeBytes() {
        java.lang.Object ref = messageType_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required bytes client_connection_public_key = 2;
      public static final int CLIENT_CONNECTION_PUBLIC_KEY_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString clientConnectionPublicKey_;
      /**
       * <code>required bytes client_connection_public_key = 2;</code>
       *
       * <pre>
       * generated using crypto_box_keypair()
       * </pre>
       */
      public boolean hasClientConnectionPublicKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes client_connection_public_key = 2;</code>
       *
       * <pre>
       * generated using crypto_box_keypair()
       * </pre>
       */
      public com.google.protobuf.ByteString getClientConnectionPublicKey() {
        return clientConnectionPublicKey_;
      }

      // required bytes hashed_server_hello = 3;
      public static final int HASHED_SERVER_HELLO_FIELD_NUMBER = 3;
      private com.google.protobuf.ByteString hashedServerHello_;
      /**
       * <code>required bytes hashed_server_hello = 3;</code>
       *
       * <pre>
       * a SHA256 hash of the received ServerHello message
       * The ClientHello includes a hash of the ServerHello to prevent replay attacks.
       * </pre>
       */
      public boolean hasHashedServerHello() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes hashed_server_hello = 3;</code>
       *
       * <pre>
       * a SHA256 hash of the received ServerHello message
       * The ClientHello includes a hash of the ServerHello to prevent replay attacks.
       * </pre>
       */
      public com.google.protobuf.ByteString getHashedServerHello() {
        return hashedServerHello_;
      }

      // required int32 length_of_server_hello = 4;
      public static final int LENGTH_OF_SERVER_HELLO_FIELD_NUMBER = 4;
      private int lengthOfServerHello_;
      /**
       * <code>required int32 length_of_server_hello = 4;</code>
       *
       * <pre>
       * the length of the ServerHello message in bytes
       * </pre>
       */
      public boolean hasLengthOfServerHello() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 length_of_server_hello = 4;</code>
       *
       * <pre>
       * the length of the ServerHello message in bytes
       * </pre>
       */
      public int getLengthOfServerHello() {
        return lengthOfServerHello_;
      }

      private void initFields() {
        messageType_ = "";
        clientConnectionPublicKey_ = com.google.protobuf.ByteString.EMPTY;
        hashedServerHello_ = com.google.protobuf.ByteString.EMPTY;
        lengthOfServerHello_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasMessageType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasClientConnectionPublicKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasHashedServerHello()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasLengthOfServerHello()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getMessageTypeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, clientConnectionPublicKey_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, hashedServerHello_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeInt32(4, lengthOfServerHello_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getMessageTypeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, clientConnectionPublicKey_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, hashedServerHello_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, lengthOfServerHello_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static messages.Clienthello.ClientHello.Handshake parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static messages.Clienthello.ClientHello.Handshake parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static messages.Clienthello.ClientHello.Handshake parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static messages.Clienthello.ClientHello.Handshake parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static messages.Clienthello.ClientHello.Handshake parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static messages.Clienthello.ClientHello.Handshake parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static messages.Clienthello.ClientHello.Handshake parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static messages.Clienthello.ClientHello.Handshake parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static messages.Clienthello.ClientHello.Handshake parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static messages.Clienthello.ClientHello.Handshake parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(messages.Clienthello.ClientHello.Handshake prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code messages.ClientHello.Handshake}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements messages.Clienthello.ClientHello.HandshakeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return messages.Clienthello.internal_static_messages_ClientHello_Handshake_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return messages.Clienthello.internal_static_messages_ClientHello_Handshake_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  messages.Clienthello.ClientHello.Handshake.class, messages.Clienthello.ClientHello.Handshake.Builder.class);
        }

        // Construct using messages.Clienthello.ClientHello.Handshake.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          messageType_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          clientConnectionPublicKey_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          hashedServerHello_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          lengthOfServerHello_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return messages.Clienthello.internal_static_messages_ClientHello_Handshake_descriptor;
        }

        public messages.Clienthello.ClientHello.Handshake getDefaultInstanceForType() {
          return messages.Clienthello.ClientHello.Handshake.getDefaultInstance();
        }

        public messages.Clienthello.ClientHello.Handshake build() {
          messages.Clienthello.ClientHello.Handshake result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public messages.Clienthello.ClientHello.Handshake buildPartial() {
          messages.Clienthello.ClientHello.Handshake result = new messages.Clienthello.ClientHello.Handshake(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.messageType_ = messageType_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.clientConnectionPublicKey_ = clientConnectionPublicKey_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.hashedServerHello_ = hashedServerHello_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.lengthOfServerHello_ = lengthOfServerHello_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof messages.Clienthello.ClientHello.Handshake) {
            return mergeFrom((messages.Clienthello.ClientHello.Handshake)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(messages.Clienthello.ClientHello.Handshake other) {
          if (other == messages.Clienthello.ClientHello.Handshake.getDefaultInstance()) return this;
          if (other.hasMessageType()) {
            bitField0_ |= 0x00000001;
            messageType_ = other.messageType_;
            onChanged();
          }
          if (other.hasClientConnectionPublicKey()) {
            setClientConnectionPublicKey(other.getClientConnectionPublicKey());
          }
          if (other.hasHashedServerHello()) {
            setHashedServerHello(other.getHashedServerHello());
          }
          if (other.hasLengthOfServerHello()) {
            setLengthOfServerHello(other.getLengthOfServerHello());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasMessageType()) {
            
            return false;
          }
          if (!hasClientConnectionPublicKey()) {
            
            return false;
          }
          if (!hasHashedServerHello()) {
            
            return false;
          }
          if (!hasLengthOfServerHello()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          messages.Clienthello.ClientHello.Handshake parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (messages.Clienthello.ClientHello.Handshake) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string message_type = 1;
        private java.lang.Object messageType_ = "";
        /**
         * <code>required string message_type = 1;</code>
         *
         * <pre>
         * opcode must always be set to "ClientHello.Handshake" to provide context for the signature and to prevent replay attacks
         * </pre>
         */
        public boolean hasMessageType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string message_type = 1;</code>
         *
         * <pre>
         * opcode must always be set to "ClientHello.Handshake" to provide context for the signature and to prevent replay attacks
         * </pre>
         */
        public java.lang.String getMessageType() {
          java.lang.Object ref = messageType_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            messageType_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string message_type = 1;</code>
         *
         * <pre>
         * opcode must always be set to "ClientHello.Handshake" to provide context for the signature and to prevent replay attacks
         * </pre>
         */
        public com.google.protobuf.ByteString
            getMessageTypeBytes() {
          java.lang.Object ref = messageType_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            messageType_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string message_type = 1;</code>
         *
         * <pre>
         * opcode must always be set to "ClientHello.Handshake" to provide context for the signature and to prevent replay attacks
         * </pre>
         */
        public Builder setMessageType(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          messageType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string message_type = 1;</code>
         *
         * <pre>
         * opcode must always be set to "ClientHello.Handshake" to provide context for the signature and to prevent replay attacks
         * </pre>
         */
        public Builder clearMessageType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          messageType_ = getDefaultInstance().getMessageType();
          onChanged();
          return this;
        }
        /**
         * <code>required string message_type = 1;</code>
         *
         * <pre>
         * opcode must always be set to "ClientHello.Handshake" to provide context for the signature and to prevent replay attacks
         * </pre>
         */
        public Builder setMessageTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          messageType_ = value;
          onChanged();
          return this;
        }

        // required bytes client_connection_public_key = 2;
        private com.google.protobuf.ByteString clientConnectionPublicKey_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes client_connection_public_key = 2;</code>
         *
         * <pre>
         * generated using crypto_box_keypair()
         * </pre>
         */
        public boolean hasClientConnectionPublicKey() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required bytes client_connection_public_key = 2;</code>
         *
         * <pre>
         * generated using crypto_box_keypair()
         * </pre>
         */
        public com.google.protobuf.ByteString getClientConnectionPublicKey() {
          return clientConnectionPublicKey_;
        }
        /**
         * <code>required bytes client_connection_public_key = 2;</code>
         *
         * <pre>
         * generated using crypto_box_keypair()
         * </pre>
         */
        public Builder setClientConnectionPublicKey(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          clientConnectionPublicKey_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes client_connection_public_key = 2;</code>
         *
         * <pre>
         * generated using crypto_box_keypair()
         * </pre>
         */
        public Builder clearClientConnectionPublicKey() {
          bitField0_ = (bitField0_ & ~0x00000002);
          clientConnectionPublicKey_ = getDefaultInstance().getClientConnectionPublicKey();
          onChanged();
          return this;
        }

        // required bytes hashed_server_hello = 3;
        private com.google.protobuf.ByteString hashedServerHello_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes hashed_server_hello = 3;</code>
         *
         * <pre>
         * a SHA256 hash of the received ServerHello message
         * The ClientHello includes a hash of the ServerHello to prevent replay attacks.
         * </pre>
         */
        public boolean hasHashedServerHello() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required bytes hashed_server_hello = 3;</code>
         *
         * <pre>
         * a SHA256 hash of the received ServerHello message
         * The ClientHello includes a hash of the ServerHello to prevent replay attacks.
         * </pre>
         */
        public com.google.protobuf.ByteString getHashedServerHello() {
          return hashedServerHello_;
        }
        /**
         * <code>required bytes hashed_server_hello = 3;</code>
         *
         * <pre>
         * a SHA256 hash of the received ServerHello message
         * The ClientHello includes a hash of the ServerHello to prevent replay attacks.
         * </pre>
         */
        public Builder setHashedServerHello(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          hashedServerHello_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes hashed_server_hello = 3;</code>
         *
         * <pre>
         * a SHA256 hash of the received ServerHello message
         * The ClientHello includes a hash of the ServerHello to prevent replay attacks.
         * </pre>
         */
        public Builder clearHashedServerHello() {
          bitField0_ = (bitField0_ & ~0x00000004);
          hashedServerHello_ = getDefaultInstance().getHashedServerHello();
          onChanged();
          return this;
        }

        // required int32 length_of_server_hello = 4;
        private int lengthOfServerHello_ ;
        /**
         * <code>required int32 length_of_server_hello = 4;</code>
         *
         * <pre>
         * the length of the ServerHello message in bytes
         * </pre>
         */
        public boolean hasLengthOfServerHello() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required int32 length_of_server_hello = 4;</code>
         *
         * <pre>
         * the length of the ServerHello message in bytes
         * </pre>
         */
        public int getLengthOfServerHello() {
          return lengthOfServerHello_;
        }
        /**
         * <code>required int32 length_of_server_hello = 4;</code>
         *
         * <pre>
         * the length of the ServerHello message in bytes
         * </pre>
         */
        public Builder setLengthOfServerHello(int value) {
          bitField0_ |= 0x00000008;
          lengthOfServerHello_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 length_of_server_hello = 4;</code>
         *
         * <pre>
         * the length of the ServerHello message in bytes
         * </pre>
         */
        public Builder clearLengthOfServerHello() {
          bitField0_ = (bitField0_ & ~0x00000008);
          lengthOfServerHello_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:messages.ClientHello.Handshake)
      }

      static {
        defaultInstance = new Handshake(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:messages.ClientHello.Handshake)
    }

    public interface SignedHandshakeOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required .messages.ClientHello.Handshake handshake = 1;
      /**
       * <code>required .messages.ClientHello.Handshake handshake = 1;</code>
       */
      boolean hasHandshake();
      /**
       * <code>required .messages.ClientHello.Handshake handshake = 1;</code>
       */
      messages.Clienthello.ClientHello.Handshake getHandshake();
      /**
       * <code>required .messages.ClientHello.Handshake handshake = 1;</code>
       */
      messages.Clienthello.ClientHello.HandshakeOrBuilder getHandshakeOrBuilder();

      // optional bytes identity_public_key = 2;
      /**
       * <code>optional bytes identity_public_key = 2;</code>
       *
       * <pre>
       * optionally reveal device identity or node identity (the device doesn't reveal its identity to the organization)
       * </pre>
       */
      boolean hasIdentityPublicKey();
      /**
       * <code>optional bytes identity_public_key = 2;</code>
       *
       * <pre>
       * optionally reveal device identity or node identity (the device doesn't reveal its identity to the organization)
       * </pre>
       */
      com.google.protobuf.ByteString getIdentityPublicKey();

      // optional bytes handshake_signature = 3;
      /**
       * <code>optional bytes handshake_signature = 3;</code>
       *
       * <pre>
       * MessageInterface: crypto_sign_detached(sk=DeviceIdentitySecretKey, msg=handshake)
       * CapabilityInterface: crypto_sign_detached(sk=NodeIdentitySecretKey, msg=handshake)
       * </pre>
       */
      boolean hasHandshakeSignature();
      /**
       * <code>optional bytes handshake_signature = 3;</code>
       *
       * <pre>
       * MessageInterface: crypto_sign_detached(sk=DeviceIdentitySecretKey, msg=handshake)
       * CapabilityInterface: crypto_sign_detached(sk=NodeIdentitySecretKey, msg=handshake)
       * </pre>
       */
      com.google.protobuf.ByteString getHandshakeSignature();

      // optional bytes numena_root_public_key = 4;
      /**
       * <code>optional bytes numena_root_public_key = 4;</code>
       *
       * <pre>
       * Our root public key
       * </pre>
       */
      boolean hasNumenaRootPublicKey();
      /**
       * <code>optional bytes numena_root_public_key = 4;</code>
       *
       * <pre>
       * Our root public key
       * </pre>
       */
      com.google.protobuf.ByteString getNumenaRootPublicKey();

      // optional bytes numena_root_signature = 5;
      /**
       * <code>optional bytes numena_root_signature = 5;</code>
       *
       * <pre>
       * Signature on the ClientHello.SignedHandshake.identity_public_key using numena_root_secret_key
       * </pre>
       */
      boolean hasNumenaRootSignature();
      /**
       * <code>optional bytes numena_root_signature = 5;</code>
       *
       * <pre>
       * Signature on the ClientHello.SignedHandshake.identity_public_key using numena_root_secret_key
       * </pre>
       */
      com.google.protobuf.ByteString getNumenaRootSignature();
    }
    /**
     * Protobuf type {@code messages.ClientHello.SignedHandshake}
     *
     * <pre>
     * this message is sent encrypted to prevent leaking the user's identity to
     * a third-party observer
     * </pre>
     */
    public static final class SignedHandshake extends
        com.google.protobuf.GeneratedMessage
        implements SignedHandshakeOrBuilder {
      // Use SignedHandshake.newBuilder() to construct.
      private SignedHandshake(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private SignedHandshake(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final SignedHandshake defaultInstance;
      public static SignedHandshake getDefaultInstance() {
        return defaultInstance;
      }

      public SignedHandshake getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private SignedHandshake(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                messages.Clienthello.ClientHello.Handshake.Builder subBuilder = null;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                  subBuilder = handshake_.toBuilder();
                }
                handshake_ = input.readMessage(messages.Clienthello.ClientHello.Handshake.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(handshake_);
                  handshake_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000001;
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                identityPublicKey_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                handshakeSignature_ = input.readBytes();
                break;
              }
              case 34: {
                bitField0_ |= 0x00000008;
                numenaRootPublicKey_ = input.readBytes();
                break;
              }
              case 42: {
                bitField0_ |= 0x00000010;
                numenaRootSignature_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return messages.Clienthello.internal_static_messages_ClientHello_SignedHandshake_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return messages.Clienthello.internal_static_messages_ClientHello_SignedHandshake_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                messages.Clienthello.ClientHello.SignedHandshake.class, messages.Clienthello.ClientHello.SignedHandshake.Builder.class);
      }

      public static com.google.protobuf.Parser<SignedHandshake> PARSER =
          new com.google.protobuf.AbstractParser<SignedHandshake>() {
        public SignedHandshake parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new SignedHandshake(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<SignedHandshake> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required .messages.ClientHello.Handshake handshake = 1;
      public static final int HANDSHAKE_FIELD_NUMBER = 1;
      private messages.Clienthello.ClientHello.Handshake handshake_;
      /**
       * <code>required .messages.ClientHello.Handshake handshake = 1;</code>
       */
      public boolean hasHandshake() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .messages.ClientHello.Handshake handshake = 1;</code>
       */
      public messages.Clienthello.ClientHello.Handshake getHandshake() {
        return handshake_;
      }
      /**
       * <code>required .messages.ClientHello.Handshake handshake = 1;</code>
       */
      public messages.Clienthello.ClientHello.HandshakeOrBuilder getHandshakeOrBuilder() {
        return handshake_;
      }

      // optional bytes identity_public_key = 2;
      public static final int IDENTITY_PUBLIC_KEY_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString identityPublicKey_;
      /**
       * <code>optional bytes identity_public_key = 2;</code>
       *
       * <pre>
       * optionally reveal device identity or node identity (the device doesn't reveal its identity to the organization)
       * </pre>
       */
      public boolean hasIdentityPublicKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes identity_public_key = 2;</code>
       *
       * <pre>
       * optionally reveal device identity or node identity (the device doesn't reveal its identity to the organization)
       * </pre>
       */
      public com.google.protobuf.ByteString getIdentityPublicKey() {
        return identityPublicKey_;
      }

      // optional bytes handshake_signature = 3;
      public static final int HANDSHAKE_SIGNATURE_FIELD_NUMBER = 3;
      private com.google.protobuf.ByteString handshakeSignature_;
      /**
       * <code>optional bytes handshake_signature = 3;</code>
       *
       * <pre>
       * MessageInterface: crypto_sign_detached(sk=DeviceIdentitySecretKey, msg=handshake)
       * CapabilityInterface: crypto_sign_detached(sk=NodeIdentitySecretKey, msg=handshake)
       * </pre>
       */
      public boolean hasHandshakeSignature() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes handshake_signature = 3;</code>
       *
       * <pre>
       * MessageInterface: crypto_sign_detached(sk=DeviceIdentitySecretKey, msg=handshake)
       * CapabilityInterface: crypto_sign_detached(sk=NodeIdentitySecretKey, msg=handshake)
       * </pre>
       */
      public com.google.protobuf.ByteString getHandshakeSignature() {
        return handshakeSignature_;
      }

      // optional bytes numena_root_public_key = 4;
      public static final int NUMENA_ROOT_PUBLIC_KEY_FIELD_NUMBER = 4;
      private com.google.protobuf.ByteString numenaRootPublicKey_;
      /**
       * <code>optional bytes numena_root_public_key = 4;</code>
       *
       * <pre>
       * Our root public key
       * </pre>
       */
      public boolean hasNumenaRootPublicKey() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes numena_root_public_key = 4;</code>
       *
       * <pre>
       * Our root public key
       * </pre>
       */
      public com.google.protobuf.ByteString getNumenaRootPublicKey() {
        return numenaRootPublicKey_;
      }

      // optional bytes numena_root_signature = 5;
      public static final int NUMENA_ROOT_SIGNATURE_FIELD_NUMBER = 5;
      private com.google.protobuf.ByteString numenaRootSignature_;
      /**
       * <code>optional bytes numena_root_signature = 5;</code>
       *
       * <pre>
       * Signature on the ClientHello.SignedHandshake.identity_public_key using numena_root_secret_key
       * </pre>
       */
      public boolean hasNumenaRootSignature() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes numena_root_signature = 5;</code>
       *
       * <pre>
       * Signature on the ClientHello.SignedHandshake.identity_public_key using numena_root_secret_key
       * </pre>
       */
      public com.google.protobuf.ByteString getNumenaRootSignature() {
        return numenaRootSignature_;
      }

      private void initFields() {
        handshake_ = messages.Clienthello.ClientHello.Handshake.getDefaultInstance();
        identityPublicKey_ = com.google.protobuf.ByteString.EMPTY;
        handshakeSignature_ = com.google.protobuf.ByteString.EMPTY;
        numenaRootPublicKey_ = com.google.protobuf.ByteString.EMPTY;
        numenaRootSignature_ = com.google.protobuf.ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasHandshake()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!getHandshake().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeMessage(1, handshake_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, identityPublicKey_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, handshakeSignature_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, numenaRootPublicKey_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeBytes(5, numenaRootSignature_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, handshake_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, identityPublicKey_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, handshakeSignature_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, numenaRootPublicKey_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(5, numenaRootSignature_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static messages.Clienthello.ClientHello.SignedHandshake parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static messages.Clienthello.ClientHello.SignedHandshake parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static messages.Clienthello.ClientHello.SignedHandshake parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static messages.Clienthello.ClientHello.SignedHandshake parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static messages.Clienthello.ClientHello.SignedHandshake parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static messages.Clienthello.ClientHello.SignedHandshake parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static messages.Clienthello.ClientHello.SignedHandshake parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static messages.Clienthello.ClientHello.SignedHandshake parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static messages.Clienthello.ClientHello.SignedHandshake parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static messages.Clienthello.ClientHello.SignedHandshake parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(messages.Clienthello.ClientHello.SignedHandshake prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code messages.ClientHello.SignedHandshake}
       *
       * <pre>
       * this message is sent encrypted to prevent leaking the user's identity to
       * a third-party observer
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements messages.Clienthello.ClientHello.SignedHandshakeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return messages.Clienthello.internal_static_messages_ClientHello_SignedHandshake_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return messages.Clienthello.internal_static_messages_ClientHello_SignedHandshake_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  messages.Clienthello.ClientHello.SignedHandshake.class, messages.Clienthello.ClientHello.SignedHandshake.Builder.class);
        }

        // Construct using messages.Clienthello.ClientHello.SignedHandshake.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getHandshakeFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          if (handshakeBuilder_ == null) {
            handshake_ = messages.Clienthello.ClientHello.Handshake.getDefaultInstance();
          } else {
            handshakeBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000001);
          identityPublicKey_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          handshakeSignature_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          numenaRootPublicKey_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000008);
          numenaRootSignature_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000010);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return messages.Clienthello.internal_static_messages_ClientHello_SignedHandshake_descriptor;
        }

        public messages.Clienthello.ClientHello.SignedHandshake getDefaultInstanceForType() {
          return messages.Clienthello.ClientHello.SignedHandshake.getDefaultInstance();
        }

        public messages.Clienthello.ClientHello.SignedHandshake build() {
          messages.Clienthello.ClientHello.SignedHandshake result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public messages.Clienthello.ClientHello.SignedHandshake buildPartial() {
          messages.Clienthello.ClientHello.SignedHandshake result = new messages.Clienthello.ClientHello.SignedHandshake(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          if (handshakeBuilder_ == null) {
            result.handshake_ = handshake_;
          } else {
            result.handshake_ = handshakeBuilder_.build();
          }
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.identityPublicKey_ = identityPublicKey_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.handshakeSignature_ = handshakeSignature_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.numenaRootPublicKey_ = numenaRootPublicKey_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.numenaRootSignature_ = numenaRootSignature_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof messages.Clienthello.ClientHello.SignedHandshake) {
            return mergeFrom((messages.Clienthello.ClientHello.SignedHandshake)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(messages.Clienthello.ClientHello.SignedHandshake other) {
          if (other == messages.Clienthello.ClientHello.SignedHandshake.getDefaultInstance()) return this;
          if (other.hasHandshake()) {
            mergeHandshake(other.getHandshake());
          }
          if (other.hasIdentityPublicKey()) {
            setIdentityPublicKey(other.getIdentityPublicKey());
          }
          if (other.hasHandshakeSignature()) {
            setHandshakeSignature(other.getHandshakeSignature());
          }
          if (other.hasNumenaRootPublicKey()) {
            setNumenaRootPublicKey(other.getNumenaRootPublicKey());
          }
          if (other.hasNumenaRootSignature()) {
            setNumenaRootSignature(other.getNumenaRootSignature());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasHandshake()) {
            
            return false;
          }
          if (!getHandshake().isInitialized()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          messages.Clienthello.ClientHello.SignedHandshake parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (messages.Clienthello.ClientHello.SignedHandshake) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required .messages.ClientHello.Handshake handshake = 1;
        private messages.Clienthello.ClientHello.Handshake handshake_ = messages.Clienthello.ClientHello.Handshake.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            messages.Clienthello.ClientHello.Handshake, messages.Clienthello.ClientHello.Handshake.Builder, messages.Clienthello.ClientHello.HandshakeOrBuilder> handshakeBuilder_;
        /**
         * <code>required .messages.ClientHello.Handshake handshake = 1;</code>
         */
        public boolean hasHandshake() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required .messages.ClientHello.Handshake handshake = 1;</code>
         */
        public messages.Clienthello.ClientHello.Handshake getHandshake() {
          if (handshakeBuilder_ == null) {
            return handshake_;
          } else {
            return handshakeBuilder_.getMessage();
          }
        }
        /**
         * <code>required .messages.ClientHello.Handshake handshake = 1;</code>
         */
        public Builder setHandshake(messages.Clienthello.ClientHello.Handshake value) {
          if (handshakeBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            handshake_ = value;
            onChanged();
          } else {
            handshakeBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        /**
         * <code>required .messages.ClientHello.Handshake handshake = 1;</code>
         */
        public Builder setHandshake(
            messages.Clienthello.ClientHello.Handshake.Builder builderForValue) {
          if (handshakeBuilder_ == null) {
            handshake_ = builderForValue.build();
            onChanged();
          } else {
            handshakeBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        /**
         * <code>required .messages.ClientHello.Handshake handshake = 1;</code>
         */
        public Builder mergeHandshake(messages.Clienthello.ClientHello.Handshake value) {
          if (handshakeBuilder_ == null) {
            if (((bitField0_ & 0x00000001) == 0x00000001) &&
                handshake_ != messages.Clienthello.ClientHello.Handshake.getDefaultInstance()) {
              handshake_ =
                messages.Clienthello.ClientHello.Handshake.newBuilder(handshake_).mergeFrom(value).buildPartial();
            } else {
              handshake_ = value;
            }
            onChanged();
          } else {
            handshakeBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        /**
         * <code>required .messages.ClientHello.Handshake handshake = 1;</code>
         */
        public Builder clearHandshake() {
          if (handshakeBuilder_ == null) {
            handshake_ = messages.Clienthello.ClientHello.Handshake.getDefaultInstance();
            onChanged();
          } else {
            handshakeBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }
        /**
         * <code>required .messages.ClientHello.Handshake handshake = 1;</code>
         */
        public messages.Clienthello.ClientHello.Handshake.Builder getHandshakeBuilder() {
          bitField0_ |= 0x00000001;
          onChanged();
          return getHandshakeFieldBuilder().getBuilder();
        }
        /**
         * <code>required .messages.ClientHello.Handshake handshake = 1;</code>
         */
        public messages.Clienthello.ClientHello.HandshakeOrBuilder getHandshakeOrBuilder() {
          if (handshakeBuilder_ != null) {
            return handshakeBuilder_.getMessageOrBuilder();
          } else {
            return handshake_;
          }
        }
        /**
         * <code>required .messages.ClientHello.Handshake handshake = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
            messages.Clienthello.ClientHello.Handshake, messages.Clienthello.ClientHello.Handshake.Builder, messages.Clienthello.ClientHello.HandshakeOrBuilder> 
            getHandshakeFieldBuilder() {
          if (handshakeBuilder_ == null) {
            handshakeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                messages.Clienthello.ClientHello.Handshake, messages.Clienthello.ClientHello.Handshake.Builder, messages.Clienthello.ClientHello.HandshakeOrBuilder>(
                    handshake_,
                    getParentForChildren(),
                    isClean());
            handshake_ = null;
          }
          return handshakeBuilder_;
        }

        // optional bytes identity_public_key = 2;
        private com.google.protobuf.ByteString identityPublicKey_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes identity_public_key = 2;</code>
         *
         * <pre>
         * optionally reveal device identity or node identity (the device doesn't reveal its identity to the organization)
         * </pre>
         */
        public boolean hasIdentityPublicKey() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional bytes identity_public_key = 2;</code>
         *
         * <pre>
         * optionally reveal device identity or node identity (the device doesn't reveal its identity to the organization)
         * </pre>
         */
        public com.google.protobuf.ByteString getIdentityPublicKey() {
          return identityPublicKey_;
        }
        /**
         * <code>optional bytes identity_public_key = 2;</code>
         *
         * <pre>
         * optionally reveal device identity or node identity (the device doesn't reveal its identity to the organization)
         * </pre>
         */
        public Builder setIdentityPublicKey(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          identityPublicKey_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes identity_public_key = 2;</code>
         *
         * <pre>
         * optionally reveal device identity or node identity (the device doesn't reveal its identity to the organization)
         * </pre>
         */
        public Builder clearIdentityPublicKey() {
          bitField0_ = (bitField0_ & ~0x00000002);
          identityPublicKey_ = getDefaultInstance().getIdentityPublicKey();
          onChanged();
          return this;
        }

        // optional bytes handshake_signature = 3;
        private com.google.protobuf.ByteString handshakeSignature_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes handshake_signature = 3;</code>
         *
         * <pre>
         * MessageInterface: crypto_sign_detached(sk=DeviceIdentitySecretKey, msg=handshake)
         * CapabilityInterface: crypto_sign_detached(sk=NodeIdentitySecretKey, msg=handshake)
         * </pre>
         */
        public boolean hasHandshakeSignature() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional bytes handshake_signature = 3;</code>
         *
         * <pre>
         * MessageInterface: crypto_sign_detached(sk=DeviceIdentitySecretKey, msg=handshake)
         * CapabilityInterface: crypto_sign_detached(sk=NodeIdentitySecretKey, msg=handshake)
         * </pre>
         */
        public com.google.protobuf.ByteString getHandshakeSignature() {
          return handshakeSignature_;
        }
        /**
         * <code>optional bytes handshake_signature = 3;</code>
         *
         * <pre>
         * MessageInterface: crypto_sign_detached(sk=DeviceIdentitySecretKey, msg=handshake)
         * CapabilityInterface: crypto_sign_detached(sk=NodeIdentitySecretKey, msg=handshake)
         * </pre>
         */
        public Builder setHandshakeSignature(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          handshakeSignature_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes handshake_signature = 3;</code>
         *
         * <pre>
         * MessageInterface: crypto_sign_detached(sk=DeviceIdentitySecretKey, msg=handshake)
         * CapabilityInterface: crypto_sign_detached(sk=NodeIdentitySecretKey, msg=handshake)
         * </pre>
         */
        public Builder clearHandshakeSignature() {
          bitField0_ = (bitField0_ & ~0x00000004);
          handshakeSignature_ = getDefaultInstance().getHandshakeSignature();
          onChanged();
          return this;
        }

        // optional bytes numena_root_public_key = 4;
        private com.google.protobuf.ByteString numenaRootPublicKey_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes numena_root_public_key = 4;</code>
         *
         * <pre>
         * Our root public key
         * </pre>
         */
        public boolean hasNumenaRootPublicKey() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional bytes numena_root_public_key = 4;</code>
         *
         * <pre>
         * Our root public key
         * </pre>
         */
        public com.google.protobuf.ByteString getNumenaRootPublicKey() {
          return numenaRootPublicKey_;
        }
        /**
         * <code>optional bytes numena_root_public_key = 4;</code>
         *
         * <pre>
         * Our root public key
         * </pre>
         */
        public Builder setNumenaRootPublicKey(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          numenaRootPublicKey_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes numena_root_public_key = 4;</code>
         *
         * <pre>
         * Our root public key
         * </pre>
         */
        public Builder clearNumenaRootPublicKey() {
          bitField0_ = (bitField0_ & ~0x00000008);
          numenaRootPublicKey_ = getDefaultInstance().getNumenaRootPublicKey();
          onChanged();
          return this;
        }

        // optional bytes numena_root_signature = 5;
        private com.google.protobuf.ByteString numenaRootSignature_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes numena_root_signature = 5;</code>
         *
         * <pre>
         * Signature on the ClientHello.SignedHandshake.identity_public_key using numena_root_secret_key
         * </pre>
         */
        public boolean hasNumenaRootSignature() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional bytes numena_root_signature = 5;</code>
         *
         * <pre>
         * Signature on the ClientHello.SignedHandshake.identity_public_key using numena_root_secret_key
         * </pre>
         */
        public com.google.protobuf.ByteString getNumenaRootSignature() {
          return numenaRootSignature_;
        }
        /**
         * <code>optional bytes numena_root_signature = 5;</code>
         *
         * <pre>
         * Signature on the ClientHello.SignedHandshake.identity_public_key using numena_root_secret_key
         * </pre>
         */
        public Builder setNumenaRootSignature(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
          numenaRootSignature_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes numena_root_signature = 5;</code>
         *
         * <pre>
         * Signature on the ClientHello.SignedHandshake.identity_public_key using numena_root_secret_key
         * </pre>
         */
        public Builder clearNumenaRootSignature() {
          bitField0_ = (bitField0_ & ~0x00000010);
          numenaRootSignature_ = getDefaultInstance().getNumenaRootSignature();
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:messages.ClientHello.SignedHandshake)
      }

      static {
        defaultInstance = new SignedHandshake(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:messages.ClientHello.SignedHandshake)
    }

    private int bitField0_;
    // required bytes client_connection_public_key = 1;
    public static final int CLIENT_CONNECTION_PUBLIC_KEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString clientConnectionPublicKey_;
    /**
     * <code>required bytes client_connection_public_key = 1;</code>
     *
     * <pre>
     * provide the pk generated in ClientHello.Handshake.client_connection_public_key to enable the server to decrypt the handshake message
     * </pre>
     */
    public boolean hasClientConnectionPublicKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes client_connection_public_key = 1;</code>
     *
     * <pre>
     * provide the pk generated in ClientHello.Handshake.client_connection_public_key to enable the server to decrypt the handshake message
     * </pre>
     */
    public com.google.protobuf.ByteString getClientConnectionPublicKey() {
      return clientConnectionPublicKey_;
    }

    // required bytes encrypted_handshake = 2;
    public static final int ENCRYPTED_HANDSHAKE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString encryptedHandshake_;
    /**
     * <code>required bytes encrypted_handshake = 2;</code>
     *
     * <pre>
     * crypto_box_easy(sk=connection_public_key, pk=ServerHello.connection_public_key, nonce=[random], msg=SignedHandshake)
     * </pre>
     */
    public boolean hasEncryptedHandshake() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes encrypted_handshake = 2;</code>
     *
     * <pre>
     * crypto_box_easy(sk=connection_public_key, pk=ServerHello.connection_public_key, nonce=[random], msg=SignedHandshake)
     * </pre>
     */
    public com.google.protobuf.ByteString getEncryptedHandshake() {
      return encryptedHandshake_;
    }

    private void initFields() {
      clientConnectionPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      encryptedHandshake_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasClientConnectionPublicKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEncryptedHandshake()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, clientConnectionPublicKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, encryptedHandshake_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, clientConnectionPublicKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, encryptedHandshake_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static messages.Clienthello.ClientHello parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Clienthello.ClientHello parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Clienthello.ClientHello parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Clienthello.ClientHello parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Clienthello.ClientHello parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static messages.Clienthello.ClientHello parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static messages.Clienthello.ClientHello parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static messages.Clienthello.ClientHello parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static messages.Clienthello.ClientHello parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static messages.Clienthello.ClientHello parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(messages.Clienthello.ClientHello prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.ClientHello}
     *
     * <pre>
     * sent in response to a ServerHello used to establish an encrypted connection
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements messages.Clienthello.ClientHelloOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return messages.Clienthello.internal_static_messages_ClientHello_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return messages.Clienthello.internal_static_messages_ClientHello_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                messages.Clienthello.ClientHello.class, messages.Clienthello.ClientHello.Builder.class);
      }

      // Construct using messages.Clienthello.ClientHello.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        clientConnectionPublicKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        encryptedHandshake_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return messages.Clienthello.internal_static_messages_ClientHello_descriptor;
      }

      public messages.Clienthello.ClientHello getDefaultInstanceForType() {
        return messages.Clienthello.ClientHello.getDefaultInstance();
      }

      public messages.Clienthello.ClientHello build() {
        messages.Clienthello.ClientHello result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public messages.Clienthello.ClientHello buildPartial() {
        messages.Clienthello.ClientHello result = new messages.Clienthello.ClientHello(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clientConnectionPublicKey_ = clientConnectionPublicKey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.encryptedHandshake_ = encryptedHandshake_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof messages.Clienthello.ClientHello) {
          return mergeFrom((messages.Clienthello.ClientHello)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(messages.Clienthello.ClientHello other) {
        if (other == messages.Clienthello.ClientHello.getDefaultInstance()) return this;
        if (other.hasClientConnectionPublicKey()) {
          setClientConnectionPublicKey(other.getClientConnectionPublicKey());
        }
        if (other.hasEncryptedHandshake()) {
          setEncryptedHandshake(other.getEncryptedHandshake());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasClientConnectionPublicKey()) {
          
          return false;
        }
        if (!hasEncryptedHandshake()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        messages.Clienthello.ClientHello parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (messages.Clienthello.ClientHello) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes client_connection_public_key = 1;
      private com.google.protobuf.ByteString clientConnectionPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes client_connection_public_key = 1;</code>
       *
       * <pre>
       * provide the pk generated in ClientHello.Handshake.client_connection_public_key to enable the server to decrypt the handshake message
       * </pre>
       */
      public boolean hasClientConnectionPublicKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes client_connection_public_key = 1;</code>
       *
       * <pre>
       * provide the pk generated in ClientHello.Handshake.client_connection_public_key to enable the server to decrypt the handshake message
       * </pre>
       */
      public com.google.protobuf.ByteString getClientConnectionPublicKey() {
        return clientConnectionPublicKey_;
      }
      /**
       * <code>required bytes client_connection_public_key = 1;</code>
       *
       * <pre>
       * provide the pk generated in ClientHello.Handshake.client_connection_public_key to enable the server to decrypt the handshake message
       * </pre>
       */
      public Builder setClientConnectionPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clientConnectionPublicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes client_connection_public_key = 1;</code>
       *
       * <pre>
       * provide the pk generated in ClientHello.Handshake.client_connection_public_key to enable the server to decrypt the handshake message
       * </pre>
       */
      public Builder clearClientConnectionPublicKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientConnectionPublicKey_ = getDefaultInstance().getClientConnectionPublicKey();
        onChanged();
        return this;
      }

      // required bytes encrypted_handshake = 2;
      private com.google.protobuf.ByteString encryptedHandshake_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes encrypted_handshake = 2;</code>
       *
       * <pre>
       * crypto_box_easy(sk=connection_public_key, pk=ServerHello.connection_public_key, nonce=[random], msg=SignedHandshake)
       * </pre>
       */
      public boolean hasEncryptedHandshake() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes encrypted_handshake = 2;</code>
       *
       * <pre>
       * crypto_box_easy(sk=connection_public_key, pk=ServerHello.connection_public_key, nonce=[random], msg=SignedHandshake)
       * </pre>
       */
      public com.google.protobuf.ByteString getEncryptedHandshake() {
        return encryptedHandshake_;
      }
      /**
       * <code>required bytes encrypted_handshake = 2;</code>
       *
       * <pre>
       * crypto_box_easy(sk=connection_public_key, pk=ServerHello.connection_public_key, nonce=[random], msg=SignedHandshake)
       * </pre>
       */
      public Builder setEncryptedHandshake(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        encryptedHandshake_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes encrypted_handshake = 2;</code>
       *
       * <pre>
       * crypto_box_easy(sk=connection_public_key, pk=ServerHello.connection_public_key, nonce=[random], msg=SignedHandshake)
       * </pre>
       */
      public Builder clearEncryptedHandshake() {
        bitField0_ = (bitField0_ & ~0x00000002);
        encryptedHandshake_ = getDefaultInstance().getEncryptedHandshake();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:messages.ClientHello)
    }

    static {
      defaultInstance = new ClientHello(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messages.ClientHello)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_ClientHello_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_ClientHello_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_ClientHello_Handshake_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_ClientHello_Handshake_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_ClientHello_SignedHandshake_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_ClientHello_SignedHandshake_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021clienthello.proto\022\010messages\"\230\003\n\013Client" +
      "Hello\022$\n\034client_connection_public_key\030\001 " +
      "\002(\014\022\033\n\023encrypted_handshake\030\002 \002(\014\032\204\001\n\tHan" +
      "dshake\022\024\n\014message_type\030\001 \002(\t\022$\n\034client_c" +
      "onnection_public_key\030\002 \002(\014\022\033\n\023hashed_ser" +
      "ver_hello\030\003 \002(\014\022\036\n\026length_of_server_hell" +
      "o\030\004 \002(\005\032\276\001\n\017SignedHandshake\0222\n\thandshake" +
      "\030\001 \002(\0132\037.messages.ClientHello.Handshake\022" +
      "\033\n\023identity_public_key\030\002 \001(\014\022\033\n\023handshak" +
      "e_signature\030\003 \001(\014\022\036\n\026numena_root_public_",
      "key\030\004 \001(\014\022\035\n\025numena_root_signature\030\005 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_messages_ClientHello_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_messages_ClientHello_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_ClientHello_descriptor,
              new java.lang.String[] { "ClientConnectionPublicKey", "EncryptedHandshake", });
          internal_static_messages_ClientHello_Handshake_descriptor =
            internal_static_messages_ClientHello_descriptor.getNestedTypes().get(0);
          internal_static_messages_ClientHello_Handshake_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_ClientHello_Handshake_descriptor,
              new java.lang.String[] { "MessageType", "ClientConnectionPublicKey", "HashedServerHello", "LengthOfServerHello", });
          internal_static_messages_ClientHello_SignedHandshake_descriptor =
            internal_static_messages_ClientHello_descriptor.getNestedTypes().get(1);
          internal_static_messages_ClientHello_SignedHandshake_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_ClientHello_SignedHandshake_descriptor,
              new java.lang.String[] { "Handshake", "IdentityPublicKey", "HandshakeSignature", "NumenaRootPublicKey", "NumenaRootSignature", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
