// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: facademessages.proto

package messages;

public final class Facademessages {
  private Facademessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SubscribeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes org_id = 1;
    /**
     * <code>required bytes org_id = 1;</code>
     */
    boolean hasOrgId();
    /**
     * <code>required bytes org_id = 1;</code>
     */
    com.google.protobuf.ByteString getOrgId();

    // required bytes app_id = 2;
    /**
     * <code>required bytes app_id = 2;</code>
     */
    boolean hasAppId();
    /**
     * <code>required bytes app_id = 2;</code>
     */
    com.google.protobuf.ByteString getAppId();

    // required bytes queue = 3;
    /**
     * <code>required bytes queue = 3;</code>
     */
    boolean hasQueue();
    /**
     * <code>required bytes queue = 3;</code>
     */
    com.google.protobuf.ByteString getQueue();

    // required bytes signed_msg = 4;
    /**
     * <code>required bytes signed_msg = 4;</code>
     */
    boolean hasSignedMsg();
    /**
     * <code>required bytes signed_msg = 4;</code>
     */
    com.google.protobuf.ByteString getSignedMsg();

    // required bytes msg_signature = 5;
    /**
     * <code>required bytes msg_signature = 5;</code>
     */
    boolean hasMsgSignature();
    /**
     * <code>required bytes msg_signature = 5;</code>
     */
    com.google.protobuf.ByteString getMsgSignature();
  }
  /**
   * Protobuf type {@code messages.Subscribe}
   */
  public static final class Subscribe extends
      com.google.protobuf.GeneratedMessage
      implements SubscribeOrBuilder {
    // Use Subscribe.newBuilder() to construct.
    private Subscribe(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Subscribe(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Subscribe defaultInstance;
    public static Subscribe getDefaultInstance() {
      return defaultInstance;
    }

    public Subscribe getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Subscribe(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              orgId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              appId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              queue_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              signedMsg_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              msgSignature_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return messages.Facademessages.internal_static_messages_Subscribe_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return messages.Facademessages.internal_static_messages_Subscribe_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              messages.Facademessages.Subscribe.class, messages.Facademessages.Subscribe.Builder.class);
    }

    public static com.google.protobuf.Parser<Subscribe> PARSER =
        new com.google.protobuf.AbstractParser<Subscribe>() {
      public Subscribe parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Subscribe(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Subscribe> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes org_id = 1;
    public static final int ORG_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString orgId_;
    /**
     * <code>required bytes org_id = 1;</code>
     */
    public boolean hasOrgId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes org_id = 1;</code>
     */
    public com.google.protobuf.ByteString getOrgId() {
      return orgId_;
    }

    // required bytes app_id = 2;
    public static final int APP_ID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString appId_;
    /**
     * <code>required bytes app_id = 2;</code>
     */
    public boolean hasAppId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes app_id = 2;</code>
     */
    public com.google.protobuf.ByteString getAppId() {
      return appId_;
    }

    // required bytes queue = 3;
    public static final int QUEUE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString queue_;
    /**
     * <code>required bytes queue = 3;</code>
     */
    public boolean hasQueue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes queue = 3;</code>
     */
    public com.google.protobuf.ByteString getQueue() {
      return queue_;
    }

    // required bytes signed_msg = 4;
    public static final int SIGNED_MSG_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString signedMsg_;
    /**
     * <code>required bytes signed_msg = 4;</code>
     */
    public boolean hasSignedMsg() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes signed_msg = 4;</code>
     */
    public com.google.protobuf.ByteString getSignedMsg() {
      return signedMsg_;
    }

    // required bytes msg_signature = 5;
    public static final int MSG_SIGNATURE_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString msgSignature_;
    /**
     * <code>required bytes msg_signature = 5;</code>
     */
    public boolean hasMsgSignature() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bytes msg_signature = 5;</code>
     */
    public com.google.protobuf.ByteString getMsgSignature() {
      return msgSignature_;
    }

    private void initFields() {
      orgId_ = com.google.protobuf.ByteString.EMPTY;
      appId_ = com.google.protobuf.ByteString.EMPTY;
      queue_ = com.google.protobuf.ByteString.EMPTY;
      signedMsg_ = com.google.protobuf.ByteString.EMPTY;
      msgSignature_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasOrgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQueue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSignedMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgSignature()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, orgId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, appId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, queue_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, signedMsg_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, msgSignature_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, orgId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, appId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, queue_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, signedMsg_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, msgSignature_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static messages.Facademessages.Subscribe parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Facademessages.Subscribe parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Facademessages.Subscribe parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Facademessages.Subscribe parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Facademessages.Subscribe parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static messages.Facademessages.Subscribe parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static messages.Facademessages.Subscribe parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static messages.Facademessages.Subscribe parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static messages.Facademessages.Subscribe parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static messages.Facademessages.Subscribe parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(messages.Facademessages.Subscribe prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.Subscribe}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements messages.Facademessages.SubscribeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return messages.Facademessages.internal_static_messages_Subscribe_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return messages.Facademessages.internal_static_messages_Subscribe_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                messages.Facademessages.Subscribe.class, messages.Facademessages.Subscribe.Builder.class);
      }

      // Construct using messages.Facademessages.Subscribe.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        orgId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        appId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        queue_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        signedMsg_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        msgSignature_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return messages.Facademessages.internal_static_messages_Subscribe_descriptor;
      }

      public messages.Facademessages.Subscribe getDefaultInstanceForType() {
        return messages.Facademessages.Subscribe.getDefaultInstance();
      }

      public messages.Facademessages.Subscribe build() {
        messages.Facademessages.Subscribe result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public messages.Facademessages.Subscribe buildPartial() {
        messages.Facademessages.Subscribe result = new messages.Facademessages.Subscribe(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.orgId_ = orgId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.appId_ = appId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.queue_ = queue_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.signedMsg_ = signedMsg_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msgSignature_ = msgSignature_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof messages.Facademessages.Subscribe) {
          return mergeFrom((messages.Facademessages.Subscribe)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(messages.Facademessages.Subscribe other) {
        if (other == messages.Facademessages.Subscribe.getDefaultInstance()) return this;
        if (other.hasOrgId()) {
          setOrgId(other.getOrgId());
        }
        if (other.hasAppId()) {
          setAppId(other.getAppId());
        }
        if (other.hasQueue()) {
          setQueue(other.getQueue());
        }
        if (other.hasSignedMsg()) {
          setSignedMsg(other.getSignedMsg());
        }
        if (other.hasMsgSignature()) {
          setMsgSignature(other.getMsgSignature());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOrgId()) {
          
          return false;
        }
        if (!hasAppId()) {
          
          return false;
        }
        if (!hasQueue()) {
          
          return false;
        }
        if (!hasSignedMsg()) {
          
          return false;
        }
        if (!hasMsgSignature()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        messages.Facademessages.Subscribe parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (messages.Facademessages.Subscribe) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes org_id = 1;
      private com.google.protobuf.ByteString orgId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes org_id = 1;</code>
       */
      public boolean hasOrgId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes org_id = 1;</code>
       */
      public com.google.protobuf.ByteString getOrgId() {
        return orgId_;
      }
      /**
       * <code>required bytes org_id = 1;</code>
       */
      public Builder setOrgId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        orgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes org_id = 1;</code>
       */
      public Builder clearOrgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        orgId_ = getDefaultInstance().getOrgId();
        onChanged();
        return this;
      }

      // required bytes app_id = 2;
      private com.google.protobuf.ByteString appId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes app_id = 2;</code>
       */
      public boolean hasAppId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes app_id = 2;</code>
       */
      public com.google.protobuf.ByteString getAppId() {
        return appId_;
      }
      /**
       * <code>required bytes app_id = 2;</code>
       */
      public Builder setAppId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes app_id = 2;</code>
       */
      public Builder clearAppId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        appId_ = getDefaultInstance().getAppId();
        onChanged();
        return this;
      }

      // required bytes queue = 3;
      private com.google.protobuf.ByteString queue_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes queue = 3;</code>
       */
      public boolean hasQueue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes queue = 3;</code>
       */
      public com.google.protobuf.ByteString getQueue() {
        return queue_;
      }
      /**
       * <code>required bytes queue = 3;</code>
       */
      public Builder setQueue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        queue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes queue = 3;</code>
       */
      public Builder clearQueue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        queue_ = getDefaultInstance().getQueue();
        onChanged();
        return this;
      }

      // required bytes signed_msg = 4;
      private com.google.protobuf.ByteString signedMsg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes signed_msg = 4;</code>
       */
      public boolean hasSignedMsg() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes signed_msg = 4;</code>
       */
      public com.google.protobuf.ByteString getSignedMsg() {
        return signedMsg_;
      }
      /**
       * <code>required bytes signed_msg = 4;</code>
       */
      public Builder setSignedMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        signedMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes signed_msg = 4;</code>
       */
      public Builder clearSignedMsg() {
        bitField0_ = (bitField0_ & ~0x00000008);
        signedMsg_ = getDefaultInstance().getSignedMsg();
        onChanged();
        return this;
      }

      // required bytes msg_signature = 5;
      private com.google.protobuf.ByteString msgSignature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes msg_signature = 5;</code>
       */
      public boolean hasMsgSignature() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bytes msg_signature = 5;</code>
       */
      public com.google.protobuf.ByteString getMsgSignature() {
        return msgSignature_;
      }
      /**
       * <code>required bytes msg_signature = 5;</code>
       */
      public Builder setMsgSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msgSignature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes msg_signature = 5;</code>
       */
      public Builder clearMsgSignature() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msgSignature_ = getDefaultInstance().getMsgSignature();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:messages.Subscribe)
    }

    static {
      defaultInstance = new Subscribe(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messages.Subscribe)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Subscribe_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_Subscribe_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024facademessages.proto\022\010messages\"e\n\tSubs" +
      "cribe\022\016\n\006org_id\030\001 \002(\014\022\016\n\006app_id\030\002 \002(\014\022\r\n" +
      "\005queue\030\003 \002(\014\022\022\n\nsigned_msg\030\004 \002(\014\022\025\n\rmsg_" +
      "signature\030\005 \002(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_messages_Subscribe_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_messages_Subscribe_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_Subscribe_descriptor,
              new java.lang.String[] { "OrgId", "AppId", "Queue", "SignedMsg", "MsgSignature", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
