// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serverhello.proto

package messages;

public final class Serverhello {
  private Serverhello() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ServerHelloOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .messages.ServerHello.Handshake handshake = 1;
    /**
     * <code>required .messages.ServerHello.Handshake handshake = 1;</code>
     */
    boolean hasHandshake();
    /**
     * <code>required .messages.ServerHello.Handshake handshake = 1;</code>
     */
    messages.Serverhello.ServerHello.Handshake getHandshake();
    /**
     * <code>required .messages.ServerHello.Handshake handshake = 1;</code>
     */
    messages.Serverhello.ServerHello.HandshakeOrBuilder getHandshakeOrBuilder();

    // required bytes handshake_signature = 2;
    /**
     * <code>required bytes handshake_signature = 2;</code>
     *
     * <pre>
     * Signature on the Handshake made using the secret key corresponding to
     *   the server_identity_public_key
     * libsodium function: crypto_sign_detached( sk=server_identity_secret_key, msg=Handshake)
     * </pre>
     */
    boolean hasHandshakeSignature();
    /**
     * <code>required bytes handshake_signature = 2;</code>
     *
     * <pre>
     * Signature on the Handshake made using the secret key corresponding to
     *   the server_identity_public_key
     * libsodium function: crypto_sign_detached( sk=server_identity_secret_key, msg=Handshake)
     * </pre>
     */
    com.google.protobuf.ByteString getHandshakeSignature();

    // required bytes server_organization_public_key = 3;
    /**
     * <code>required bytes server_organization_public_key = 3;</code>
     *
     * <pre>
     *   Facade: numena_root_public_key
     *   OrganizationServer: OrganizationIdentityPublicKey
     * </pre>
     */
    boolean hasServerOrganizationPublicKey();
    /**
     * <code>required bytes server_organization_public_key = 3;</code>
     *
     * <pre>
     *   Facade: numena_root_public_key
     *   OrganizationServer: OrganizationIdentityPublicKey
     * </pre>
     */
    com.google.protobuf.ByteString getServerOrganizationPublicKey();

    // required bytes server_organization_signature = 4;
    /**
     * <code>required bytes server_organization_signature = 4;</code>
     *
     * <pre>
     * Signature on the server_identity_public_key made using server_organization_secret_key
     * </pre>
     */
    boolean hasServerOrganizationSignature();
    /**
     * <code>required bytes server_organization_signature = 4;</code>
     *
     * <pre>
     * Signature on the server_identity_public_key made using server_organization_secret_key
     * </pre>
     */
    com.google.protobuf.ByteString getServerOrganizationSignature();
  }
  /**
   * Protobuf type {@code messages.ServerHello}
   *
   * <pre>
   * sent by the server at the beginning of each connection
   * </pre>
   */
  public static final class ServerHello extends
      com.google.protobuf.GeneratedMessage
      implements ServerHelloOrBuilder {
    // Use ServerHello.newBuilder() to construct.
    private ServerHello(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServerHello(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServerHello defaultInstance;
    public static ServerHello getDefaultInstance() {
      return defaultInstance;
    }

    public ServerHello getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServerHello(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              messages.Serverhello.ServerHello.Handshake.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = handshake_.toBuilder();
              }
              handshake_ = input.readMessage(messages.Serverhello.ServerHello.Handshake.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(handshake_);
                handshake_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              handshakeSignature_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              serverOrganizationPublicKey_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              serverOrganizationSignature_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return messages.Serverhello.internal_static_messages_ServerHello_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return messages.Serverhello.internal_static_messages_ServerHello_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              messages.Serverhello.ServerHello.class, messages.Serverhello.ServerHello.Builder.class);
    }

    public static com.google.protobuf.Parser<ServerHello> PARSER =
        new com.google.protobuf.AbstractParser<ServerHello>() {
      public ServerHello parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerHello(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServerHello> getParserForType() {
      return PARSER;
    }

    public interface HandshakeOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string message_type = 1;
      /**
       * <code>required string message_type = 1;</code>
       *
       * <pre>
       * opcode must always be set to "ServerHello.Handshake" to provide context for the signature and to prevent replay attacks
       * </pre>
       */
      boolean hasMessageType();
      /**
       * <code>required string message_type = 1;</code>
       *
       * <pre>
       * opcode must always be set to "ServerHello.Handshake" to provide context for the signature and to prevent replay attacks
       * </pre>
       */
      java.lang.String getMessageType();
      /**
       * <code>required string message_type = 1;</code>
       *
       * <pre>
       * opcode must always be set to "ServerHello.Handshake" to provide context for the signature and to prevent replay attacks
       * </pre>
       */
      com.google.protobuf.ByteString
          getMessageTypeBytes();

      // required bytes server_connection_public_key = 2;
      /**
       * <code>required bytes server_connection_public_key = 2;</code>
       *
       * <pre>
       * ephemeral key public key, generated using crypto_box_keypair()
       * </pre>
       */
      boolean hasServerConnectionPublicKey();
      /**
       * <code>required bytes server_connection_public_key = 2;</code>
       *
       * <pre>
       * ephemeral key public key, generated using crypto_box_keypair()
       * </pre>
       */
      com.google.protobuf.ByteString getServerConnectionPublicKey();

      // required int64 timestamp_now = 3;
      /**
       * <code>required int64 timestamp_now = 3;</code>
       *
       * <pre>
       * current UNIX timestamp in seconds (since jan 1st 1970)
       * to prevent replay attacks
       * </pre>
       */
      boolean hasTimestampNow();
      /**
       * <code>required int64 timestamp_now = 3;</code>
       *
       * <pre>
       * current UNIX timestamp in seconds (since jan 1st 1970)
       * to prevent replay attacks
       * </pre>
       */
      long getTimestampNow();

      // required bytes server_identity_public_key = 4;
      /**
       * <code>required bytes server_identity_public_key = 4;</code>
       *
       * <pre>
       *   Facade: NodeIdentityPublicKey
       *   Organization: OrganizationServerIdentityPublicKey
       * </pre>
       */
      boolean hasServerIdentityPublicKey();
      /**
       * <code>required bytes server_identity_public_key = 4;</code>
       *
       * <pre>
       *   Facade: NodeIdentityPublicKey
       *   Organization: OrganizationServerIdentityPublicKey
       * </pre>
       */
      com.google.protobuf.ByteString getServerIdentityPublicKey();
    }
    /**
     * Protobuf type {@code messages.ServerHello.Handshake}
     */
    public static final class Handshake extends
        com.google.protobuf.GeneratedMessage
        implements HandshakeOrBuilder {
      // Use Handshake.newBuilder() to construct.
      private Handshake(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Handshake(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Handshake defaultInstance;
      public static Handshake getDefaultInstance() {
        return defaultInstance;
      }

      public Handshake getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Handshake(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                messageType_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                serverConnectionPublicKey_ = input.readBytes();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                timestampNow_ = input.readInt64();
                break;
              }
              case 34: {
                bitField0_ |= 0x00000008;
                serverIdentityPublicKey_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return messages.Serverhello.internal_static_messages_ServerHello_Handshake_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return messages.Serverhello.internal_static_messages_ServerHello_Handshake_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                messages.Serverhello.ServerHello.Handshake.class, messages.Serverhello.ServerHello.Handshake.Builder.class);
      }

      public static com.google.protobuf.Parser<Handshake> PARSER =
          new com.google.protobuf.AbstractParser<Handshake>() {
        public Handshake parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Handshake(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Handshake> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string message_type = 1;
      public static final int MESSAGE_TYPE_FIELD_NUMBER = 1;
      private java.lang.Object messageType_;
      /**
       * <code>required string message_type = 1;</code>
       *
       * <pre>
       * opcode must always be set to "ServerHello.Handshake" to provide context for the signature and to prevent replay attacks
       * </pre>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string message_type = 1;</code>
       *
       * <pre>
       * opcode must always be set to "ServerHello.Handshake" to provide context for the signature and to prevent replay attacks
       * </pre>
       */
      public java.lang.String getMessageType() {
        java.lang.Object ref = messageType_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            messageType_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string message_type = 1;</code>
       *
       * <pre>
       * opcode must always be set to "ServerHello.Handshake" to provide context for the signature and to prevent replay attacks
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMessageTypeBytes() {
        java.lang.Object ref = messageType_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required bytes server_connection_public_key = 2;
      public static final int SERVER_CONNECTION_PUBLIC_KEY_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString serverConnectionPublicKey_;
      /**
       * <code>required bytes server_connection_public_key = 2;</code>
       *
       * <pre>
       * ephemeral key public key, generated using crypto_box_keypair()
       * </pre>
       */
      public boolean hasServerConnectionPublicKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes server_connection_public_key = 2;</code>
       *
       * <pre>
       * ephemeral key public key, generated using crypto_box_keypair()
       * </pre>
       */
      public com.google.protobuf.ByteString getServerConnectionPublicKey() {
        return serverConnectionPublicKey_;
      }

      // required int64 timestamp_now = 3;
      public static final int TIMESTAMP_NOW_FIELD_NUMBER = 3;
      private long timestampNow_;
      /**
       * <code>required int64 timestamp_now = 3;</code>
       *
       * <pre>
       * current UNIX timestamp in seconds (since jan 1st 1970)
       * to prevent replay attacks
       * </pre>
       */
      public boolean hasTimestampNow() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 timestamp_now = 3;</code>
       *
       * <pre>
       * current UNIX timestamp in seconds (since jan 1st 1970)
       * to prevent replay attacks
       * </pre>
       */
      public long getTimestampNow() {
        return timestampNow_;
      }

      // required bytes server_identity_public_key = 4;
      public static final int SERVER_IDENTITY_PUBLIC_KEY_FIELD_NUMBER = 4;
      private com.google.protobuf.ByteString serverIdentityPublicKey_;
      /**
       * <code>required bytes server_identity_public_key = 4;</code>
       *
       * <pre>
       *   Facade: NodeIdentityPublicKey
       *   Organization: OrganizationServerIdentityPublicKey
       * </pre>
       */
      public boolean hasServerIdentityPublicKey() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes server_identity_public_key = 4;</code>
       *
       * <pre>
       *   Facade: NodeIdentityPublicKey
       *   Organization: OrganizationServerIdentityPublicKey
       * </pre>
       */
      public com.google.protobuf.ByteString getServerIdentityPublicKey() {
        return serverIdentityPublicKey_;
      }

      private void initFields() {
        messageType_ = "";
        serverConnectionPublicKey_ = com.google.protobuf.ByteString.EMPTY;
        timestampNow_ = 0L;
        serverIdentityPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasMessageType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasServerConnectionPublicKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasTimestampNow()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasServerIdentityPublicKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getMessageTypeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, serverConnectionPublicKey_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt64(3, timestampNow_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, serverIdentityPublicKey_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getMessageTypeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, serverConnectionPublicKey_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(3, timestampNow_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, serverIdentityPublicKey_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static messages.Serverhello.ServerHello.Handshake parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static messages.Serverhello.ServerHello.Handshake parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static messages.Serverhello.ServerHello.Handshake parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static messages.Serverhello.ServerHello.Handshake parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static messages.Serverhello.ServerHello.Handshake parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static messages.Serverhello.ServerHello.Handshake parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static messages.Serverhello.ServerHello.Handshake parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static messages.Serverhello.ServerHello.Handshake parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static messages.Serverhello.ServerHello.Handshake parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static messages.Serverhello.ServerHello.Handshake parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(messages.Serverhello.ServerHello.Handshake prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code messages.ServerHello.Handshake}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements messages.Serverhello.ServerHello.HandshakeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return messages.Serverhello.internal_static_messages_ServerHello_Handshake_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return messages.Serverhello.internal_static_messages_ServerHello_Handshake_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  messages.Serverhello.ServerHello.Handshake.class, messages.Serverhello.ServerHello.Handshake.Builder.class);
        }

        // Construct using messages.Serverhello.ServerHello.Handshake.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          messageType_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          serverConnectionPublicKey_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          timestampNow_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000004);
          serverIdentityPublicKey_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return messages.Serverhello.internal_static_messages_ServerHello_Handshake_descriptor;
        }

        public messages.Serverhello.ServerHello.Handshake getDefaultInstanceForType() {
          return messages.Serverhello.ServerHello.Handshake.getDefaultInstance();
        }

        public messages.Serverhello.ServerHello.Handshake build() {
          messages.Serverhello.ServerHello.Handshake result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public messages.Serverhello.ServerHello.Handshake buildPartial() {
          messages.Serverhello.ServerHello.Handshake result = new messages.Serverhello.ServerHello.Handshake(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.messageType_ = messageType_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.serverConnectionPublicKey_ = serverConnectionPublicKey_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.timestampNow_ = timestampNow_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.serverIdentityPublicKey_ = serverIdentityPublicKey_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof messages.Serverhello.ServerHello.Handshake) {
            return mergeFrom((messages.Serverhello.ServerHello.Handshake)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(messages.Serverhello.ServerHello.Handshake other) {
          if (other == messages.Serverhello.ServerHello.Handshake.getDefaultInstance()) return this;
          if (other.hasMessageType()) {
            bitField0_ |= 0x00000001;
            messageType_ = other.messageType_;
            onChanged();
          }
          if (other.hasServerConnectionPublicKey()) {
            setServerConnectionPublicKey(other.getServerConnectionPublicKey());
          }
          if (other.hasTimestampNow()) {
            setTimestampNow(other.getTimestampNow());
          }
          if (other.hasServerIdentityPublicKey()) {
            setServerIdentityPublicKey(other.getServerIdentityPublicKey());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasMessageType()) {
            
            return false;
          }
          if (!hasServerConnectionPublicKey()) {
            
            return false;
          }
          if (!hasTimestampNow()) {
            
            return false;
          }
          if (!hasServerIdentityPublicKey()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          messages.Serverhello.ServerHello.Handshake parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (messages.Serverhello.ServerHello.Handshake) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string message_type = 1;
        private java.lang.Object messageType_ = "";
        /**
         * <code>required string message_type = 1;</code>
         *
         * <pre>
         * opcode must always be set to "ServerHello.Handshake" to provide context for the signature and to prevent replay attacks
         * </pre>
         */
        public boolean hasMessageType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string message_type = 1;</code>
         *
         * <pre>
         * opcode must always be set to "ServerHello.Handshake" to provide context for the signature and to prevent replay attacks
         * </pre>
         */
        public java.lang.String getMessageType() {
          java.lang.Object ref = messageType_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            messageType_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string message_type = 1;</code>
         *
         * <pre>
         * opcode must always be set to "ServerHello.Handshake" to provide context for the signature and to prevent replay attacks
         * </pre>
         */
        public com.google.protobuf.ByteString
            getMessageTypeBytes() {
          java.lang.Object ref = messageType_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            messageType_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string message_type = 1;</code>
         *
         * <pre>
         * opcode must always be set to "ServerHello.Handshake" to provide context for the signature and to prevent replay attacks
         * </pre>
         */
        public Builder setMessageType(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          messageType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string message_type = 1;</code>
         *
         * <pre>
         * opcode must always be set to "ServerHello.Handshake" to provide context for the signature and to prevent replay attacks
         * </pre>
         */
        public Builder clearMessageType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          messageType_ = getDefaultInstance().getMessageType();
          onChanged();
          return this;
        }
        /**
         * <code>required string message_type = 1;</code>
         *
         * <pre>
         * opcode must always be set to "ServerHello.Handshake" to provide context for the signature and to prevent replay attacks
         * </pre>
         */
        public Builder setMessageTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          messageType_ = value;
          onChanged();
          return this;
        }

        // required bytes server_connection_public_key = 2;
        private com.google.protobuf.ByteString serverConnectionPublicKey_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes server_connection_public_key = 2;</code>
         *
         * <pre>
         * ephemeral key public key, generated using crypto_box_keypair()
         * </pre>
         */
        public boolean hasServerConnectionPublicKey() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required bytes server_connection_public_key = 2;</code>
         *
         * <pre>
         * ephemeral key public key, generated using crypto_box_keypair()
         * </pre>
         */
        public com.google.protobuf.ByteString getServerConnectionPublicKey() {
          return serverConnectionPublicKey_;
        }
        /**
         * <code>required bytes server_connection_public_key = 2;</code>
         *
         * <pre>
         * ephemeral key public key, generated using crypto_box_keypair()
         * </pre>
         */
        public Builder setServerConnectionPublicKey(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          serverConnectionPublicKey_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes server_connection_public_key = 2;</code>
         *
         * <pre>
         * ephemeral key public key, generated using crypto_box_keypair()
         * </pre>
         */
        public Builder clearServerConnectionPublicKey() {
          bitField0_ = (bitField0_ & ~0x00000002);
          serverConnectionPublicKey_ = getDefaultInstance().getServerConnectionPublicKey();
          onChanged();
          return this;
        }

        // required int64 timestamp_now = 3;
        private long timestampNow_ ;
        /**
         * <code>required int64 timestamp_now = 3;</code>
         *
         * <pre>
         * current UNIX timestamp in seconds (since jan 1st 1970)
         * to prevent replay attacks
         * </pre>
         */
        public boolean hasTimestampNow() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required int64 timestamp_now = 3;</code>
         *
         * <pre>
         * current UNIX timestamp in seconds (since jan 1st 1970)
         * to prevent replay attacks
         * </pre>
         */
        public long getTimestampNow() {
          return timestampNow_;
        }
        /**
         * <code>required int64 timestamp_now = 3;</code>
         *
         * <pre>
         * current UNIX timestamp in seconds (since jan 1st 1970)
         * to prevent replay attacks
         * </pre>
         */
        public Builder setTimestampNow(long value) {
          bitField0_ |= 0x00000004;
          timestampNow_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int64 timestamp_now = 3;</code>
         *
         * <pre>
         * current UNIX timestamp in seconds (since jan 1st 1970)
         * to prevent replay attacks
         * </pre>
         */
        public Builder clearTimestampNow() {
          bitField0_ = (bitField0_ & ~0x00000004);
          timestampNow_ = 0L;
          onChanged();
          return this;
        }

        // required bytes server_identity_public_key = 4;
        private com.google.protobuf.ByteString serverIdentityPublicKey_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes server_identity_public_key = 4;</code>
         *
         * <pre>
         *   Facade: NodeIdentityPublicKey
         *   Organization: OrganizationServerIdentityPublicKey
         * </pre>
         */
        public boolean hasServerIdentityPublicKey() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required bytes server_identity_public_key = 4;</code>
         *
         * <pre>
         *   Facade: NodeIdentityPublicKey
         *   Organization: OrganizationServerIdentityPublicKey
         * </pre>
         */
        public com.google.protobuf.ByteString getServerIdentityPublicKey() {
          return serverIdentityPublicKey_;
        }
        /**
         * <code>required bytes server_identity_public_key = 4;</code>
         *
         * <pre>
         *   Facade: NodeIdentityPublicKey
         *   Organization: OrganizationServerIdentityPublicKey
         * </pre>
         */
        public Builder setServerIdentityPublicKey(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          serverIdentityPublicKey_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes server_identity_public_key = 4;</code>
         *
         * <pre>
         *   Facade: NodeIdentityPublicKey
         *   Organization: OrganizationServerIdentityPublicKey
         * </pre>
         */
        public Builder clearServerIdentityPublicKey() {
          bitField0_ = (bitField0_ & ~0x00000008);
          serverIdentityPublicKey_ = getDefaultInstance().getServerIdentityPublicKey();
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:messages.ServerHello.Handshake)
      }

      static {
        defaultInstance = new Handshake(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:messages.ServerHello.Handshake)
    }

    private int bitField0_;
    // required .messages.ServerHello.Handshake handshake = 1;
    public static final int HANDSHAKE_FIELD_NUMBER = 1;
    private messages.Serverhello.ServerHello.Handshake handshake_;
    /**
     * <code>required .messages.ServerHello.Handshake handshake = 1;</code>
     */
    public boolean hasHandshake() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .messages.ServerHello.Handshake handshake = 1;</code>
     */
    public messages.Serverhello.ServerHello.Handshake getHandshake() {
      return handshake_;
    }
    /**
     * <code>required .messages.ServerHello.Handshake handshake = 1;</code>
     */
    public messages.Serverhello.ServerHello.HandshakeOrBuilder getHandshakeOrBuilder() {
      return handshake_;
    }

    // required bytes handshake_signature = 2;
    public static final int HANDSHAKE_SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString handshakeSignature_;
    /**
     * <code>required bytes handshake_signature = 2;</code>
     *
     * <pre>
     * Signature on the Handshake made using the secret key corresponding to
     *   the server_identity_public_key
     * libsodium function: crypto_sign_detached( sk=server_identity_secret_key, msg=Handshake)
     * </pre>
     */
    public boolean hasHandshakeSignature() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes handshake_signature = 2;</code>
     *
     * <pre>
     * Signature on the Handshake made using the secret key corresponding to
     *   the server_identity_public_key
     * libsodium function: crypto_sign_detached( sk=server_identity_secret_key, msg=Handshake)
     * </pre>
     */
    public com.google.protobuf.ByteString getHandshakeSignature() {
      return handshakeSignature_;
    }

    // required bytes server_organization_public_key = 3;
    public static final int SERVER_ORGANIZATION_PUBLIC_KEY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString serverOrganizationPublicKey_;
    /**
     * <code>required bytes server_organization_public_key = 3;</code>
     *
     * <pre>
     *   Facade: numena_root_public_key
     *   OrganizationServer: OrganizationIdentityPublicKey
     * </pre>
     */
    public boolean hasServerOrganizationPublicKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes server_organization_public_key = 3;</code>
     *
     * <pre>
     *   Facade: numena_root_public_key
     *   OrganizationServer: OrganizationIdentityPublicKey
     * </pre>
     */
    public com.google.protobuf.ByteString getServerOrganizationPublicKey() {
      return serverOrganizationPublicKey_;
    }

    // required bytes server_organization_signature = 4;
    public static final int SERVER_ORGANIZATION_SIGNATURE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString serverOrganizationSignature_;
    /**
     * <code>required bytes server_organization_signature = 4;</code>
     *
     * <pre>
     * Signature on the server_identity_public_key made using server_organization_secret_key
     * </pre>
     */
    public boolean hasServerOrganizationSignature() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes server_organization_signature = 4;</code>
     *
     * <pre>
     * Signature on the server_identity_public_key made using server_organization_secret_key
     * </pre>
     */
    public com.google.protobuf.ByteString getServerOrganizationSignature() {
      return serverOrganizationSignature_;
    }

    private void initFields() {
      handshake_ = messages.Serverhello.ServerHello.Handshake.getDefaultInstance();
      handshakeSignature_ = com.google.protobuf.ByteString.EMPTY;
      serverOrganizationPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      serverOrganizationSignature_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasHandshake()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHandshakeSignature()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerOrganizationPublicKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerOrganizationSignature()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHandshake().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, handshake_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, handshakeSignature_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, serverOrganizationPublicKey_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, serverOrganizationSignature_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, handshake_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, handshakeSignature_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, serverOrganizationPublicKey_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, serverOrganizationSignature_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static messages.Serverhello.ServerHello parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Serverhello.ServerHello parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Serverhello.ServerHello parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.Serverhello.ServerHello parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.Serverhello.ServerHello parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static messages.Serverhello.ServerHello parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static messages.Serverhello.ServerHello parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static messages.Serverhello.ServerHello parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static messages.Serverhello.ServerHello parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static messages.Serverhello.ServerHello parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(messages.Serverhello.ServerHello prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.ServerHello}
     *
     * <pre>
     * sent by the server at the beginning of each connection
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements messages.Serverhello.ServerHelloOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return messages.Serverhello.internal_static_messages_ServerHello_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return messages.Serverhello.internal_static_messages_ServerHello_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                messages.Serverhello.ServerHello.class, messages.Serverhello.ServerHello.Builder.class);
      }

      // Construct using messages.Serverhello.ServerHello.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHandshakeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (handshakeBuilder_ == null) {
          handshake_ = messages.Serverhello.ServerHello.Handshake.getDefaultInstance();
        } else {
          handshakeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        handshakeSignature_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        serverOrganizationPublicKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        serverOrganizationSignature_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return messages.Serverhello.internal_static_messages_ServerHello_descriptor;
      }

      public messages.Serverhello.ServerHello getDefaultInstanceForType() {
        return messages.Serverhello.ServerHello.getDefaultInstance();
      }

      public messages.Serverhello.ServerHello build() {
        messages.Serverhello.ServerHello result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public messages.Serverhello.ServerHello buildPartial() {
        messages.Serverhello.ServerHello result = new messages.Serverhello.ServerHello(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (handshakeBuilder_ == null) {
          result.handshake_ = handshake_;
        } else {
          result.handshake_ = handshakeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.handshakeSignature_ = handshakeSignature_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.serverOrganizationPublicKey_ = serverOrganizationPublicKey_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.serverOrganizationSignature_ = serverOrganizationSignature_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof messages.Serverhello.ServerHello) {
          return mergeFrom((messages.Serverhello.ServerHello)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(messages.Serverhello.ServerHello other) {
        if (other == messages.Serverhello.ServerHello.getDefaultInstance()) return this;
        if (other.hasHandshake()) {
          mergeHandshake(other.getHandshake());
        }
        if (other.hasHandshakeSignature()) {
          setHandshakeSignature(other.getHandshakeSignature());
        }
        if (other.hasServerOrganizationPublicKey()) {
          setServerOrganizationPublicKey(other.getServerOrganizationPublicKey());
        }
        if (other.hasServerOrganizationSignature()) {
          setServerOrganizationSignature(other.getServerOrganizationSignature());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHandshake()) {
          
          return false;
        }
        if (!hasHandshakeSignature()) {
          
          return false;
        }
        if (!hasServerOrganizationPublicKey()) {
          
          return false;
        }
        if (!hasServerOrganizationSignature()) {
          
          return false;
        }
        if (!getHandshake().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        messages.Serverhello.ServerHello parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (messages.Serverhello.ServerHello) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .messages.ServerHello.Handshake handshake = 1;
      private messages.Serverhello.ServerHello.Handshake handshake_ = messages.Serverhello.ServerHello.Handshake.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          messages.Serverhello.ServerHello.Handshake, messages.Serverhello.ServerHello.Handshake.Builder, messages.Serverhello.ServerHello.HandshakeOrBuilder> handshakeBuilder_;
      /**
       * <code>required .messages.ServerHello.Handshake handshake = 1;</code>
       */
      public boolean hasHandshake() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .messages.ServerHello.Handshake handshake = 1;</code>
       */
      public messages.Serverhello.ServerHello.Handshake getHandshake() {
        if (handshakeBuilder_ == null) {
          return handshake_;
        } else {
          return handshakeBuilder_.getMessage();
        }
      }
      /**
       * <code>required .messages.ServerHello.Handshake handshake = 1;</code>
       */
      public Builder setHandshake(messages.Serverhello.ServerHello.Handshake value) {
        if (handshakeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          handshake_ = value;
          onChanged();
        } else {
          handshakeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .messages.ServerHello.Handshake handshake = 1;</code>
       */
      public Builder setHandshake(
          messages.Serverhello.ServerHello.Handshake.Builder builderForValue) {
        if (handshakeBuilder_ == null) {
          handshake_ = builderForValue.build();
          onChanged();
        } else {
          handshakeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .messages.ServerHello.Handshake handshake = 1;</code>
       */
      public Builder mergeHandshake(messages.Serverhello.ServerHello.Handshake value) {
        if (handshakeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              handshake_ != messages.Serverhello.ServerHello.Handshake.getDefaultInstance()) {
            handshake_ =
              messages.Serverhello.ServerHello.Handshake.newBuilder(handshake_).mergeFrom(value).buildPartial();
          } else {
            handshake_ = value;
          }
          onChanged();
        } else {
          handshakeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .messages.ServerHello.Handshake handshake = 1;</code>
       */
      public Builder clearHandshake() {
        if (handshakeBuilder_ == null) {
          handshake_ = messages.Serverhello.ServerHello.Handshake.getDefaultInstance();
          onChanged();
        } else {
          handshakeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .messages.ServerHello.Handshake handshake = 1;</code>
       */
      public messages.Serverhello.ServerHello.Handshake.Builder getHandshakeBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHandshakeFieldBuilder().getBuilder();
      }
      /**
       * <code>required .messages.ServerHello.Handshake handshake = 1;</code>
       */
      public messages.Serverhello.ServerHello.HandshakeOrBuilder getHandshakeOrBuilder() {
        if (handshakeBuilder_ != null) {
          return handshakeBuilder_.getMessageOrBuilder();
        } else {
          return handshake_;
        }
      }
      /**
       * <code>required .messages.ServerHello.Handshake handshake = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          messages.Serverhello.ServerHello.Handshake, messages.Serverhello.ServerHello.Handshake.Builder, messages.Serverhello.ServerHello.HandshakeOrBuilder> 
          getHandshakeFieldBuilder() {
        if (handshakeBuilder_ == null) {
          handshakeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              messages.Serverhello.ServerHello.Handshake, messages.Serverhello.ServerHello.Handshake.Builder, messages.Serverhello.ServerHello.HandshakeOrBuilder>(
                  handshake_,
                  getParentForChildren(),
                  isClean());
          handshake_ = null;
        }
        return handshakeBuilder_;
      }

      // required bytes handshake_signature = 2;
      private com.google.protobuf.ByteString handshakeSignature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes handshake_signature = 2;</code>
       *
       * <pre>
       * Signature on the Handshake made using the secret key corresponding to
       *   the server_identity_public_key
       * libsodium function: crypto_sign_detached( sk=server_identity_secret_key, msg=Handshake)
       * </pre>
       */
      public boolean hasHandshakeSignature() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes handshake_signature = 2;</code>
       *
       * <pre>
       * Signature on the Handshake made using the secret key corresponding to
       *   the server_identity_public_key
       * libsodium function: crypto_sign_detached( sk=server_identity_secret_key, msg=Handshake)
       * </pre>
       */
      public com.google.protobuf.ByteString getHandshakeSignature() {
        return handshakeSignature_;
      }
      /**
       * <code>required bytes handshake_signature = 2;</code>
       *
       * <pre>
       * Signature on the Handshake made using the secret key corresponding to
       *   the server_identity_public_key
       * libsodium function: crypto_sign_detached( sk=server_identity_secret_key, msg=Handshake)
       * </pre>
       */
      public Builder setHandshakeSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        handshakeSignature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes handshake_signature = 2;</code>
       *
       * <pre>
       * Signature on the Handshake made using the secret key corresponding to
       *   the server_identity_public_key
       * libsodium function: crypto_sign_detached( sk=server_identity_secret_key, msg=Handshake)
       * </pre>
       */
      public Builder clearHandshakeSignature() {
        bitField0_ = (bitField0_ & ~0x00000002);
        handshakeSignature_ = getDefaultInstance().getHandshakeSignature();
        onChanged();
        return this;
      }

      // required bytes server_organization_public_key = 3;
      private com.google.protobuf.ByteString serverOrganizationPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes server_organization_public_key = 3;</code>
       *
       * <pre>
       *   Facade: numena_root_public_key
       *   OrganizationServer: OrganizationIdentityPublicKey
       * </pre>
       */
      public boolean hasServerOrganizationPublicKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes server_organization_public_key = 3;</code>
       *
       * <pre>
       *   Facade: numena_root_public_key
       *   OrganizationServer: OrganizationIdentityPublicKey
       * </pre>
       */
      public com.google.protobuf.ByteString getServerOrganizationPublicKey() {
        return serverOrganizationPublicKey_;
      }
      /**
       * <code>required bytes server_organization_public_key = 3;</code>
       *
       * <pre>
       *   Facade: numena_root_public_key
       *   OrganizationServer: OrganizationIdentityPublicKey
       * </pre>
       */
      public Builder setServerOrganizationPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serverOrganizationPublicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes server_organization_public_key = 3;</code>
       *
       * <pre>
       *   Facade: numena_root_public_key
       *   OrganizationServer: OrganizationIdentityPublicKey
       * </pre>
       */
      public Builder clearServerOrganizationPublicKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serverOrganizationPublicKey_ = getDefaultInstance().getServerOrganizationPublicKey();
        onChanged();
        return this;
      }

      // required bytes server_organization_signature = 4;
      private com.google.protobuf.ByteString serverOrganizationSignature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes server_organization_signature = 4;</code>
       *
       * <pre>
       * Signature on the server_identity_public_key made using server_organization_secret_key
       * </pre>
       */
      public boolean hasServerOrganizationSignature() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes server_organization_signature = 4;</code>
       *
       * <pre>
       * Signature on the server_identity_public_key made using server_organization_secret_key
       * </pre>
       */
      public com.google.protobuf.ByteString getServerOrganizationSignature() {
        return serverOrganizationSignature_;
      }
      /**
       * <code>required bytes server_organization_signature = 4;</code>
       *
       * <pre>
       * Signature on the server_identity_public_key made using server_organization_secret_key
       * </pre>
       */
      public Builder setServerOrganizationSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        serverOrganizationSignature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes server_organization_signature = 4;</code>
       *
       * <pre>
       * Signature on the server_identity_public_key made using server_organization_secret_key
       * </pre>
       */
      public Builder clearServerOrganizationSignature() {
        bitField0_ = (bitField0_ & ~0x00000008);
        serverOrganizationSignature_ = getDefaultInstance().getServerOrganizationSignature();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:messages.ServerHello)
    }

    static {
      defaultInstance = new ServerHello(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messages.ServerHello)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_ServerHello_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_ServerHello_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_ServerHello_Handshake_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_ServerHello_Handshake_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021serverhello.proto\022\010messages\"\262\002\n\013Server" +
      "Hello\0222\n\thandshake\030\001 \002(\0132\037.messages.Serv" +
      "erHello.Handshake\022\033\n\023handshake_signature" +
      "\030\002 \002(\014\022&\n\036server_organization_public_key" +
      "\030\003 \002(\014\022%\n\035server_organization_signature\030" +
      "\004 \002(\014\032\202\001\n\tHandshake\022\024\n\014message_type\030\001 \002(" +
      "\t\022$\n\034server_connection_public_key\030\002 \002(\014\022" +
      "\025\n\rtimestamp_now\030\003 \002(\003\022\"\n\032server_identit" +
      "y_public_key\030\004 \002(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_messages_ServerHello_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_messages_ServerHello_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_ServerHello_descriptor,
              new java.lang.String[] { "Handshake", "HandshakeSignature", "ServerOrganizationPublicKey", "ServerOrganizationSignature", });
          internal_static_messages_ServerHello_Handshake_descriptor =
            internal_static_messages_ServerHello_descriptor.getNestedTypes().get(0);
          internal_static_messages_ServerHello_Handshake_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_ServerHello_Handshake_descriptor,
              new java.lang.String[] { "MessageType", "ServerConnectionPublicKey", "TimestampNow", "ServerIdentityPublicKey", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
